### 2. Data Preprocessing

This notebook prepares the processed Sydney air quality data for exploratory analysis and subsequent modelling. The preprocessing decisions are based on the data-quality issues identified during the data inspection stage.

#### 2.1 Setup and Project Settings

In [1]:
# Import the libraries needed for data preprocessing.
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Set the main project folders.
processed_dir = Path("../data/processed")
results_dir = Path("../results")
tables_dir = results_dir / "tables"

# These are the seven stations retained during data inspection.
retained_stations = [
    "Camden",
    "Liverpool",
    "Parramatta North",
    "Penrith",
    "Prospect",
    "Randwick",
    "Rozelle"
]

print("Preprocessing setup complete.")

Preprocessing setup complete.

#### 2.2 Variables Used for Analysis

The analysis focuses on PM2.5 as the target variable and uses available meteorological and pollutant variables as explanatory variables.

In [3]:
# These are the variables identified for the project.
# PM2.5 is the target, while the other variables are potential predictors.

target_variable = "PM2.5"

predictor_variables = [
    "TEMP",
    "HUMID",
    "WSP",
    "WDR",
    "RAIN",
    "PM10",
    "NO2",
    "CO",
    "NO",
    "OZONE",
    "SO2"
]

print("Target variable:", target_variable)
print("Number of potential predictors:", len(predictor_variables))

Target variable: PM2.5
Number of potential predictors: 11

#### 2.3 Combine Variables Within Each Station

The processed files contain different variables for the same monitoring station. They are combined using the timestamp so that each row represents one hourly observation for a station.

##### 2.3.1 Check for Duplicate Timestamps

In [4]:
# Check whether any processed files contain duplicate timestamps.
# This is important before combining the variables because duplicate
# timestamps can create many-to-many merges.

duplicate_summary = []

for station in retained_stations:

    station_dir = processed_dir / station

    for file in station_dir.glob("*.xlsx"):

        df = pd.read_excel(file, header=2)

        # Create one datetime value from the separate Date and Time columns.
        df["Datetime"] = pd.to_datetime(
            df["Date"].astype(str) + " " + df["Time"].astype(str),
            errors="coerce",
            dayfirst=True
        )

        duplicate_count = df["Datetime"].duplicated().sum()

        duplicate_summary.append({
            "Station": station,
            "File": file.name,
            "Duplicate_Timestamps": duplicate_count
        })

duplicate_df = pd.DataFrame(duplicate_summary)

# Only display files where duplicate timestamps were found.
duplicate_flagged = duplicate_df[
    duplicate_df["Duplicate_Timestamps"] > 0
]

display(duplicate_flagged)

,Station,File,Duplicate_Timestamps
0,Camden,"Air Temperature, Relative Humidity.xlsx",2390
1,Camden,"NO2, CO, SO2.xlsx",2390
2,Camden,"Ozone, NO.xlsx",2390
3,Camden,"PM10, PM2.5, Ammonia.xlsx",2390
4,Camden,Rainfall.xlsx,2390
5,Camden,"Wind Speed, Wind Direction.xlsx",2390
6,Liverpool,"Air Temperature, Relative Humidity.xlsx",2390
7,Liverpool,"NO2, CO.xlsx",2390
8,Liverpool,"Ozone, NO.xlsx",2390
9,Liverpool,"PM2.5, Ammonia.xlsx",2390
10,Liverpool,Rainfall.xlsx,2390
11,Liverpool,"SO2, PM10.xlsx",2390
12,Liverpool,"Wind Speed, Wind Direction.xlsx",2390
13,Parramatta North,"Air Temperature, Relative Humidity.xlsx",2390
14,Parramatta North,"NO2, CO.xlsx",2390
15,Parramatta North,"Ozone, NO.xlsx",2390
16,Parramatta North,"PM2.5, Ammonia.xlsx",2390
17,Parramatta North,Rainfall.xlsx,2390
18,Parramatta North,"SO2, PM10.xlsx",2390
19,Parramatta North,"Wind speed, Wind Direction.xlsx",2390
20,Penrith,"Air Temperature, Relative humidity.xlsx",2390
21,Penrith,"NO2, CO.xlsx",2390
22,Penrith,"Ozone, NO.xlsx",2390
23,Penrith,"PM2.5, Ammonia.xlsx",2390
24,Penrith,Rainfall.xlsx,2390
25,Penrith,"SO2, PM10.xlsx",2390
26,Penrith,"Wind Speed, Wind Direction.xlsx",2390
27,Prospect,"Air Temperature, Relative Humidity, Rainfall.xlsx",2390
28,Prospect,"NO2, CO.xlsx",2390
29,Prospect,"Ozone, NO.xlsx",2390
30,Prospect,"PM2.5, Ammonia.xlsx",2390
31,Prospect,"SO2, PM10.xlsx",2390
32,Prospect,"Wind Speed, Wind Direction.xlsx",2390
33,Randwick,"Air Temperature, Relative Humidity.xlsx",2390
34,Randwick,"NO2, CO, SO2.xlsx",2390
35,Randwick,Ozone and NO.xlsx,2390
36,Randwick,"PM10, PM2.5, Ammonia.xlsx",2390
37,Randwick,Rainfall.xlsx,2390
38,Randwick,"Wind Speed, Wind Direction.xlsx",2390
39,Rozelle,"Air Temperature, Relative Humidity.xlsx",2390
40,Rozelle,"NO2, CO.xlsx",2390
41,Rozelle,"Ozone, NO.xlsx",2390
42,Rozelle,"PM2.5, Ammonia.xlsx",2390
43,Rozelle,Rainfall.xlsx,2390
44,Rozelle,"SO2, PM10.xlsx",2390
45,Rozelle,"Wind Speed, Wind Direction.xlsx",2390

##### 2.3.2 Inspect Duplicate Timestamp Records

In [5]:
# Inspect a few duplicate timestamps from one processed file.
# We want to check whether the duplicate rows contain the same
# measurements or whether they contain different values.

sample_file = (
    processed_dir
    / "Camden"
    / "Air Temperature, Relative Humidity.xlsx"
)

sample_df = pd.read_excel(sample_file, header=2)

# Create one datetime value from the separate Date and Time columns.
sample_df["Datetime"] = pd.to_datetime(
    sample_df["Date"].astype(str) + " " + sample_df["Time"].astype(str),
    errors="coerce",
    dayfirst=True
)

# Keep only rows where the timestamp occurs more than once.
duplicate_rows = sample_df[
    sample_df["Datetime"].duplicated(keep=False)
].sort_values("Datetime")

display(duplicate_rows.head(20))

,Date,Time,CAMDEN TEMP 1h average [°C],CAMDEN HUMID 1h average [%],Datetime
23,01/01/2020,24:00,19.7,67.8,NaT
47,02/01/2020,24:00,20.4,86.0,NaT
71,03/01/2020,24:00,22.5,76.8,NaT
95,04/01/2020,24:00,25.5,44.9,NaT
119,05/01/2020,24:00,18.5,69.6,NaT
143,06/01/2020,24:00,20.1,86.5,NaT
167,07/01/2020,24:00,NaN,NaN,NaT
191,08/01/2020,24:00,21.6,68.1,NaT
215,09/01/2020,24:00,21.8,80.8,NaT
239,10/01/2020,24:00,25.9,67.2,NaT
263,11/01/2020,24:00,19.5,67.3,NaT
287,12/01/2020,24:00,15.8,97.6,NaT
311,13/01/2020,24:00,18.1,86.3,NaT
335,14/01/2020,24:00,19.3,84.6,NaT
359,15/01/2020,24:00,21.8,86.2,NaT
383,16/01/2020,24:00,18.9,99.0,NaT
407,17/01/2020,24:00,19.7,89.7,NaT
431,18/01/2020,24:00,18.6,97.4,NaT
455,19/01/2020,24:00,20.2,99.2,NaT
479,20/01/2020,24:00,19.6,92.6,NaT

##### 2.3.3 Combine Variables Within Each Station

In [6]:
# Combine all available variables into one hourly dataset for each station.
# The timestamp handling follows the approach already used in Notebook 01,
# including the conversion of "24:00" to midnight on the following day.

station_data = {}

for station in retained_stations:

    station_dir = processed_dir / station
    file_data = []

    for file in station_dir.glob("*.xlsx"):

        # Read the processed Excel file.
        df = pd.read_excel(file, header=2)

        # Identify the date and time columns.
        date_col = "Date"
        time_col = "Time"

        # Convert the date column to datetime.
        df[date_col] = pd.to_datetime(
            df[date_col],
            format="%d/%m/%Y",
            errors="coerce"
        )

        # Convert the time column to text.
        df[time_col] = df[time_col].astype(str).str.strip()

        # Handle "24:00" in the same way as Notebook 01.
        midnight_24 = df[time_col] == "24:00"

        df.loc[midnight_24, time_col] = "00:00"

        df.loc[midnight_24, date_col] = (
            df.loc[midnight_24, date_col]
            + pd.Timedelta(days=1)
        )

        # Create one combined timestamp.
        df["Datetime"] = pd.to_datetime(
            df[date_col].dt.strftime("%d/%m/%Y")
            + " "
            + df[time_col],
            format="%d/%m/%Y %H:%M",
            errors="coerce"
        )

        # Keep only the timestamp and measurement columns.
        measurement_columns = [
            col for col in df.columns
            if col not in [date_col, time_col, "Datetime"]
        ]

        df = df[["Datetime"] + measurement_columns]

        # Convert measurement columns to numeric values.
        for column in measurement_columns:
            df[column] = pd.to_numeric(df[column], errors="coerce")

        # Remove any rows where a valid timestamp could not be created.
        df = df.dropna(subset=["Datetime"])

        # Store this file for combining later.
        file_data.append(df)

    # Combine the files using Datetime rather than repeated many-to-many merges.
    if file_data:
        station_df = file_data[0].copy()

        for next_df in file_data[1:]:
            station_df = station_df.set_index("Datetime").join(
                next_df.set_index("Datetime"),
                how="outer"
            ).reset_index()

        # Sort the final station data chronologically.
        station_df = station_df.sort_values("Datetime").reset_index(drop=True)

        station_data[station] = station_df

        print(
            f"{station}: {station_df.shape[0]:,} rows, "
            f"{station_df.shape[1] - 1} measurement columns"
        )

print("\nAll retained station files have been combined.")

Camden: 57,384 rows, 11 measurement columns
Liverpool: 57,384 rows, 12 measurement columns
Parramatta North: 57,384 rows, 12 measurement columns
Penrith: 57,384 rows, 12 measurement columns
Prospect: 57,384 rows, 11 measurement columns
Randwick: 57,384 rows, 11 measurement columns
Rozelle: 57,384 rows, 12 measurement columns

All retained station files have been combined.

##### 2.3.4 Check Combined Station Data

In [7]:
# Check the structure of the combined data for each retained station.
# This confirms that the timestamps and measurement columns were
# combined correctly before we start cleaning the data.

for station in retained_stations:

    station_df = station_data[station]

    print(f"\n{station}")
    print("Shape:", station_df.shape)
    print("First timestamp:", station_df["Datetime"].min())
    print("Last timestamp:", station_df["Datetime"].max())

    display(station_df.head(3))

Camden
Shape: (57384, 12)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,CAMDEN TEMP 1h average [°C],CAMDEN HUMID 1h average [%],CAMDEN NO2 1h average [pphm],CAMDEN CO 1h average [ppm],CAMDEN NO 1h average [pphm],CAMDEN OZONE 1h average [pphm],CAMDEN PM10 1h average [µg/m³],CAMDEN PM2.5 1h average [µg/m³],CAMDEN RAIN 1h average [mm/m²],CAMDEN WDR 1h average [°],CAMDEN WSP 1h average [m/s]
0,2020-01-01 01:00:00,19.4,49.9,0.3,0.2,0.0,1.9,55.9,49.8,NaN,164.2,1.3
1,2020-01-01 02:00:00,18.5,59.3,NaN,NaN,NaN,NaN,35.3,31.4,NaN,179.5,1.6
2,2020-01-01 03:00:00,18.5,59.3,0.2,0.2,0.0,1.7,42.2,23.5,NaN,204.0,1.6

Liverpool
Shape: (57384, 13)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,LIVERPOOL TEMP 1h average [°C],LIVERPOOL HUMID 1h average [%],LIVERPOOL NO2 1h average [pphm],LIVERPOOL CO 1h average [ppm],LIVERPOOL NO 1h average [pphm],LIVERPOOL OZONE 1h average [pphm],LIVERPOOL PM2.5 1h average [µg/m³],LIVERPOOL RAIN 1h average [mm/m²],LIVERPOOL SO2 1h average [pphm],LIVERPOOL PM10 1h average [µg/m³],LIVERPOOL WDR 1h average [°],LIVERPOOL WSP 1h average [m/s]
0,2020-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Parramatta North
Shape: (57384, 13)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,PARRAMATTA NORTH TEMP 1h average [°C],PARRAMATTA NORTH HUMID 1h average [%],PARRAMATTA NORTH NO2 1h average [pphm],PARRAMATTA NORTH CO 1h average [ppm],PARRAMATTA NORTH NO 1h average [pphm],PARRAMATTA NORTH OZONE 1h average [pphm],PARRAMATTA NORTH PM2.5 1h average [µg/m³],PARRAMATTA NORTH RAIN 1h average [mm/m²],PARRAMATTA NORTH SO2 1h average [pphm],PARRAMATTA NORTH PM10 1h average [µg/m³],PARRAMATTA NORTH WDR 1h average [°],PARRAMATTA NORTH WSP 1h average [m/s]
0,2020-01-01 01:00:00,19.5,65.6,0.0,0.1,0.0,2.0,13.2,NaN,0.0,39.1,180.1,1.4
1,2020-01-01 02:00:00,19.4,68.1,NaN,NaN,NaN,NaN,9.3,NaN,NaN,42.8,188.9,1.3
2,2020-01-01 03:00:00,19.4,68.2,0.1,0.1,0.0,1.7,7.4,NaN,0.1,41.1,193.8,1.2

Penrith
Shape: (57384, 13)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,PENRITH TEMP 1h average [°C],PENRITH HUMID 1h average [%],PENRITH NO2 1h average [pphm],PENRITH CO 1h average [ppm],PENRITH NO 1h average [pphm],PENRITH OZONE 1h average [pphm],PENRITH PM2.5 1h average [µg/m³],PENRITH RAIN 1h average [mm/m²],PENRITH SO2 1h average [pphm],PENRITH PM10 1h average [µg/m³],PENRITH WDR 1h average [°],PENRITH WSP 1h average [m/s]
0,2020-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Prospect
Shape: (57384, 12)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,PROSPECT TEMP 1h average [°C],PROSPECT HUMID 1h average [%],PROSPECT NO2 1h average [pphm],PROSPECT CO 1h average [ppm],PROSPECT NO 1h average [pphm],PROSPECT OZONE 1h average [pphm],PROSPECT PM2.5 1h average [µg/m³],PROSPECT SO2 1h average [pphm],PROSPECT PM10 1h average [µg/m³],PROSPECT WDR 1h average [°],PROSPECT WSP 1h average [m/s]
0,2020-01-01 01:00:00,19.3,66.2,0.2,0.1,-0.1,1.7,24.0,0.1,58.0,187.4,2.2
1,2020-01-01 02:00:00,19.2,68.1,NaN,NaN,NaN,NaN,17.2,NaN,37.2,201.6,2.2
2,2020-01-01 03:00:00,19.1,69.1,0.1,0.0,-0.1,1.8,9.0,0.0,39.8,196.8,2.2

Randwick
Shape: (57384, 12)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,RANDWICK TEMP 1h average [°C],RANDWICK HUMID 1h average [%],RANDWICK SO2 1h average [pphm],RANDWICK NO2 1h average [pphm],RANDWICK NO 1h average [pphm],RANDWICK OZONE 1h average [pphm],RANDWICK PM10 1h average [µg/m³],RANDWICK PM2.5 1h average [µg/m³],RANDWICK RAIN 1h average [mm/m²],RANDWICK WDR 1h average [°],RANDWICK WSP 1h average [m/s]
0,2020-01-01 01:00:00,19.5,73.0,0.0,0.0,-0.1,2.0,40.9,18.5,NaN,191.5,3.8
1,2020-01-01 02:00:00,19.0,74.6,NaN,NaN,NaN,NaN,45.4,8.1,NaN,214.1,3.6
2,2020-01-01 03:00:00,18.3,71.4,0.0,0.4,0.0,1.4,39.7,15.0,NaN,221.6,4.2

Rozelle
Shape: (57384, 13)
First timestamp: 2020-01-01 01:00:00
Last timestamp: 2026-07-19 00:00:00

,Datetime,ROZELLE TEMP 1h average [°C],ROZELLE HUMID 1h average [%],ROZELLE NO2 1h average [pphm],ROZELLE CO 1h average [ppm],ROZELLE NO 1h average [pphm],ROZELLE OZONE 1h average [pphm],ROZELLE PM2.5 1h average [µg/m³],ROZELLE RAIN 1h average [mm/m²],ROZELLE SO2 1h average [pphm],ROZELLE PM10 1h average [µg/m³],ROZELLE WDR 1h average [°],ROZELLE WSP 1h average [m/s]
0,2020-01-01 01:00:00,19.0,71.5,0.1,0.1,0.0,1.8,10.2,0.0,0.0,36.6,190.2,2.5
1,2020-01-01 02:00:00,19.0,71.6,NaN,NaN,NaN,NaN,10.9,0.0,NaN,35.2,188.9,2.2
2,2020-01-01 03:00:00,18.8,70.2,0.0,0.1,0.0,1.8,12.4,0.0,0.0,35.9,193.0,1.9

#### 2.4 Clean Invalid and Suspicious Values

##### 2.4.1 Convert Invalid Values to Missing

In [8]:
# Replace physically invalid measurements with NaN.
# We keep the rows themselves because other variables may still
# contain useful measurements at the same timestamp.

cleaned_station_data = {}

for station in retained_stations:

    df = station_data[station].copy()

    # Identify the measurement columns for this station.
    measurement_columns = [
        column for column in df.columns
        if column != "Datetime"
    ]

    # Apply physical validity rules to the measurement columns.
    for column in measurement_columns:

        column_upper = column.upper()

        # Humidity must be between 0% and 100%.
        if "HUMID" in column_upper:
            invalid = (df[column] < 0) | (df[column] > 100)

        # PM2.5 and PM10 concentrations cannot be negative.
        elif "PM2.5" in column_upper or "PM10" in column_upper:
            invalid = df[column] < 0

        # Wind direction must be between 0° and 360°.
        elif "WDR" in column_upper:
            invalid = (df[column] < 0) | (df[column] > 360)

        # Wind speed and rainfall cannot be negative.
        elif "WSP" in column_upper or "RAIN" in column_upper:
            invalid = df[column] < 0

        # Other pollutant concentrations cannot be negative.
        elif any(
            pollutant in column_upper
            for pollutant in ["NO2", "NO", "CO", "OZONE", "SO2"]
        ):
            invalid = df[column] < 0

        else:
            continue

        # Replace invalid measurements with NaN.
        df.loc[invalid, column] = np.nan

    cleaned_station_data[station] = df

print("Invalid measurements have been converted to NaN.")

Invalid measurements have been converted to NaN.

##### 2.4.2 Summary of Cleaned Invalid Values

In [9]:
# Count how many invalid measurements were converted to NaN
# for each station and variable.

cleaning_summary = []

for station in retained_stations:

    original_df = station_data[station]
    cleaned_df = cleaned_station_data[station]

    for column in original_df.columns:

        if column == "Datetime":
            continue

        # Count values that were present before cleaning
        # but are now missing.
        changed_to_nan = (
            original_df[column].notna()
            & cleaned_df[column].isna()
        ).sum()

        if changed_to_nan > 0:
            cleaning_summary.append({
                "Station": station,
                "Variable": column,
                "Values_Converted_to_NaN": changed_to_nan
            })

cleaning_summary_df = pd.DataFrame(cleaning_summary)

display(
    cleaning_summary_df.sort_values(
        "Values_Converted_to_NaN",
        ascending=False
    )
)

,Station,Variable,Values_Converted_to_NaN
9,Liverpool,LIVERPOOL CO 1h average [ppm],28387
25,Penrith,PENRITH CO 1h average [ppm],16458
33,Prospect,PROSPECT CO 1h average [ppm],13187
18,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],8301
2,Camden,CAMDEN CO 1h average [ppm],7299
6,Camden,CAMDEN PM2.5 1h average [µg/m³],6901
34,Prospect,PROSPECT NO 1h average [pphm],5167
35,Prospect,PROSPECT PM2.5 1h average [µg/m³],5056
28,Penrith,PENRITH PM2.5 1h average [µg/m³],4660
44,Randwick,RANDWICK PM2.5 1h average [µg/m³],4653
12,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],4447
3,Camden,CAMDEN NO 1h average [pphm],4444
49,Rozelle,ROZELLE PM2.5 1h average [µg/m³],3158
20,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],3093
47,Rozelle,ROZELLE NO 1h average [pphm],3047
40,Randwick,RANDWICK NO2 1h average [pphm],2601
24,Penrith,PENRITH NO2 1h average [pphm],2367
0,Camden,CAMDEN HUMID 1h average [%],2291
45,Rozelle,ROZELLE NO2 1h average [pphm],2274
8,Liverpool,LIVERPOOL NO2 1h average [pphm],2119
10,Liverpool,LIVERPOOL NO 1h average [pphm],2069
26,Penrith,PENRITH NO 1h average [pphm],1988
32,Prospect,PROSPECT NO2 1h average [pphm],1863
38,Randwick,RANDWICK HUMID 1h average [%],1744
41,Randwick,RANDWICK NO 1h average [pphm],1502
46,Rozelle,ROZELLE CO 1h average [ppm],1251
17,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],999
50,Rozelle,ROZELLE SO2 1h average [pphm],967
23,Penrith,PENRITH HUMID 1h average [%],963
5,Camden,CAMDEN PM10 1h average [µg/m³],944
31,Prospect,PROSPECT HUMID 1h average [%],858
22,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],585
37,Prospect,PROSPECT PM10 1h average [µg/m³],545
16,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],505
30,Penrith,PENRITH PM10 1h average [µg/m³],494
7,Liverpool,LIVERPOOL HUMID 1h average [%],475
51,Rozelle,ROZELLE PM10 1h average [µg/m³],467
14,Liverpool,LIVERPOOL PM10 1h average [µg/m³],437
13,Liverpool,LIVERPOOL SO2 1h average [pphm],435
43,Randwick,RANDWICK PM10 1h average [µg/m³],432
39,Randwick,RANDWICK SO2 1h average [pphm],353
29,Penrith,PENRITH SO2 1h average [pphm],228
21,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],214
36,Prospect,PROSPECT SO2 1h average [pphm],194
15,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],158
27,Penrith,PENRITH OZONE 1h average [pphm],42
11,Liverpool,LIVERPOOL OZONE 1h average [pphm],33
4,Camden,CAMDEN OZONE 1h average [pphm],29
1,Camden,CAMDEN NO2 1h average [pphm],21
48,Rozelle,ROZELLE OZONE 1h average [pphm],7
19,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],4
42,Randwick,RANDWICK OZONE 1h average [pphm],1

#### 2.5 Missing-Value Assessment After Cleaning

##### 2.5.1 Missing Values After Invalid-Value Cleaning

In [ ]:
# Check how much missing data remains after invalid measurements
# have been converted to NaN.

missing_after_cleaning = []

for station in retained_stations:

    df = cleaned_station_data[station]

    for column in df.columns:

        if column == "Datetime":
            continue

        missing_count = df[column].isna().sum()
        total_count = len(df)

        missing_percentage = (
            missing_count / total_count
        ) * 100

        missing_after_cleaning.append({
            "Station": station,
            "Variable": column,
            "Missing_Values": missing_count,
            "Total_Values": total_count,
            "Missing_Percentage": missing_percentage
        })

missing_after_cleaning_df = pd.DataFrame(
    missing_after_cleaning
)

#Displays full table
pd.set_option("display.max_rows", None)
display(
    missing_after_cleaning_df.sort_values(
        "Missing_Percentage",
        ascending=False
    )
)

,Station,Variable,Missing_Values,Total_Values,Missing_Percentage
14,Liverpool,LIVERPOOL CO 1h average [ppm],34628,57384,60.344347
38,Penrith,PENRITH CO 1h average [ppm],25478,57384,44.399136
66,Randwick,RANDWICK RAIN 1h average [mm/m²],24524,57384,42.736651
30,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],20625,57384,35.942074
50,Prospect,PROSPECT CO 1h average [ppm],17284,57384,30.119894
8,Camden,CAMDEN RAIN 1h average [mm/m²],15164,57384,26.425484
18,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],15035,57384,26.200683
3,Camden,CAMDEN CO 1h average [ppm],13361,57384,23.283494
27,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],12553,57384,21.875436
41,Penrith,PENRITH PM2.5 1h average [µg/m³],10433,57384,18.181026
4,Camden,CAMDEN NO 1h average [pphm],10291,57384,17.933570
37,Penrith,PENRITH NO2 1h average [pphm],10226,57384,17.820298
7,Camden,CAMDEN PM2.5 1h average [µg/m³],9941,57384,17.323644
39,Penrith,PENRITH NO 1h average [pphm],9850,57384,17.165063
51,Prospect,PROSPECT NO 1h average [pphm],9114,57384,15.882476
53,Prospect,PROSPECT PM2.5 1h average [µg/m³],8986,57384,15.659417
43,Penrith,PENRITH SO2 1h average [pphm],7690,57384,13.400948
73,Rozelle,ROZELLE NO 1h average [pphm],7185,57384,12.520912
40,Penrith,PENRITH OZONE 1h average [pphm],6975,57384,12.154956
61,Randwick,RANDWICK NO2 1h average [pphm],6967,57384,12.141015
17,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],6617,57384,11.531089
71,Rozelle,ROZELLE NO2 1h average [pphm],6407,57384,11.165133
36,Penrith,PENRITH HUMID 1h average [%],6388,57384,11.132023
65,Randwick,RANDWICK PM2.5 1h average [µg/m³],6169,57384,10.750383
13,Liverpool,LIVERPOOL NO2 1h average [pphm],6010,57384,10.473303
15,Liverpool,LIVERPOOL NO 1h average [pphm],5962,57384,10.389656
44,Penrith,PENRITH PM10 1h average [µg/m³],5953,57384,10.373972
72,Rozelle,ROZELLE CO 1h average [ppm],5898,57384,10.278126
62,Randwick,RANDWICK NO 1h average [pphm],5873,57384,10.234560
2,Camden,CAMDEN NO2 1h average [pphm],5865,57384,10.220619
49,Prospect,PROSPECT NO2 1h average [pphm],5809,57384,10.123031
77,Rozelle,ROZELLE SO2 1h average [pphm],5573,57384,9.711766
29,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],5486,57384,9.560156
35,Penrith,PENRITH TEMP 1h average [°C],5394,57384,9.399833
5,Camden,CAMDEN OZONE 1h average [pphm],5363,57384,9.345811
42,Penrith,PENRITH RAIN 1h average [mm/m²],4775,57384,8.321135
25,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],4760,57384,8.294995
45,Penrith,PENRITH WDR 1h average [°],4538,57384,7.908128
46,Penrith,PENRITH WSP 1h average [m/s],4538,57384,7.908128
75,Rozelle,ROZELLE PM2.5 1h average [µg/m³],4479,57384,7.805312
60,Randwick,RANDWICK SO2 1h average [pphm],4345,57384,7.571797
26,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],4336,57384,7.556113
19,Liverpool,LIVERPOOL SO2 1h average [pphm],4246,57384,7.399275
16,Liverpool,LIVERPOOL OZONE 1h average [pphm],3862,57384,6.730099
54,Prospect,PROSPECT SO2 1h average [pphm],3634,57384,6.332776
74,Rozelle,ROZELLE OZONE 1h average [pphm],3577,57384,6.233445
31,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],3430,57384,5.977276
59,Randwick,RANDWICK HUMID 1h average [%],3254,57384,5.670570
63,Randwick,RANDWICK OZONE 1h average [pphm],3242,57384,5.649658
1,Camden,CAMDEN HUMID 1h average [%],3211,57384,5.595636
52,Prospect,PROSPECT OZONE 1h average [pphm],3186,57384,5.552070
28,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],2563,57384,4.466402
67,Randwick,RANDWICK WDR 1h average [°],2190,57384,3.816395
68,Randwick,RANDWICK WSP 1h average [m/s],2190,57384,3.816395
6,Camden,CAMDEN PM10 1h average [µg/m³],2184,57384,3.805939
55,Prospect,PROSPECT PM10 1h average [µg/m³],2130,57384,3.711836
78,Rozelle,ROZELLE PM10 1h average [µg/m³],1707,57384,2.974697
76,Rozelle,ROZELLE RAIN 1h average [mm/m²],1651,57384,2.877109
48,Prospect,PROSPECT HUMID 1h average [%],1637,57384,2.852712
58,Randwick,RANDWICK TEMP 1h average [°C],1494,57384,2.603513
20,Liverpool,LIVERPOOL PM10 1h average [µg/m³],1450,57384,2.526837
64,Randwick,RANDWICK PM10 1h average [µg/m³],1373,57384,2.392653
32,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],1339,57384,2.333403
12,Liverpool,LIVERPOOL HUMID 1h average [%],1296,57384,2.258469
0,Camden,CAMDEN TEMP 1h average [°C],904,57384,1.575352
70,Rozelle,ROZELLE HUMID 1h average [%],878,57384,1.530043
69,Rozelle,ROZELLE TEMP 1h average [°C],862,57384,1.502161
11,Liverpool,LIVERPOOL TEMP 1h average [°C],780,57384,1.359264
9,Camden,CAMDEN WDR 1h average [°],764,57384,1.331382
47,Prospect,PROSPECT TEMP 1h average [°C],763,57384,1.329639
10,Camden,CAMDEN WSP 1h average [m/s],759,57384,1.322668
56,Prospect,PROSPECT WDR 1h average [°],716,57384,1.247735
57,Prospect,PROSPECT WSP 1h average [m/s],715,57384,1.245992
79,Rozelle,ROZELLE WDR 1h average [°],646,57384,1.125749
80,Rozelle,ROZELLE WSP 1h average [m/s],646,57384,1.125749
24,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],586,57384,1.021191
23,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],413,57384,0.719713
21,Liverpool,LIVERPOOL WDR 1h average [°],399,57384,0.695316
22,Liverpool,LIVERPOOL WSP 1h average [m/s],399,57384,0.695316
33,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],103,57384,0.179493
34,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],103,57384,0.179493

##### 2.5.2 Identify Identify Consecutive Missing-Value Gaps after converting to Invalid Values

In [13]:
# Find consecutive periods of missing values for each station and variable.
# This helps us distinguish short gaps, which may be suitable for
# interpolation, from long gaps, which should be left missing.

gap_summary = []

for station in retained_stations:

    df = cleaned_station_data[station].copy()

    for column in df.columns:

        if column == "Datetime":
            continue

        # Identify missing and non-missing observations.
        is_missing = df[column].isna()

        # Give each consecutive missing period a unique group number.
        gap_group = (
            is_missing.ne(is_missing.shift())
            .cumsum()
        )

        # Calculate the length of each missing period.
        gap_lengths = (
            df.loc[is_missing]
            .groupby(gap_group[is_missing])
            .size()
        )

        if len(gap_lengths) > 0:

            gap_summary.append({
                "Station": station,
                "Variable": column,
                "Number_of_Gaps": len(gap_lengths),
                "Longest_Gap_Hours": gap_lengths.max(),
                "Average_Gap_Hours": gap_lengths.mean()
            })

gap_summary_df = pd.DataFrame(gap_summary)

display(
    gap_summary_df.sort_values(
        "Longest_Gap_Hours",
        ascending=False
    )
)

,Station,Variable,Number_of_Gaps,Longest_Gap_Hours,Average_Gap_Hours
66,Randwick,RANDWICK RAIN 1h average [mm/m²],36,24037,681.222222
30,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],34,20487,606.617647
18,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],73,14800,205.958904
8,Camden,CAMDEN RAIN 1h average [mm/m²],73,14488,207.726027
38,Penrith,PENRITH CO 1h average [ppm],2233,4442,11.409763
40,Penrith,PENRITH OZONE 1h average [pphm],2060,4442,3.385922
43,Penrith,PENRITH SO2 1h average [pphm],2085,4442,3.688249
45,Penrith,PENRITH WDR 1h average [°],46,4427,98.652174
46,Penrith,PENRITH WSP 1h average [m/s],46,4427,98.652174
41,Penrith,PENRITH PM2.5 1h average [µg/m³],2809,4384,3.714133
44,Penrith,PENRITH PM10 1h average [µg/m³],554,4384,10.745487
42,Penrith,PENRITH RAIN 1h average [mm/m²],65,4382,73.461538
39,Penrith,PENRITH NO 1h average [pphm],2680,4370,3.675373
37,Penrith,PENRITH NO2 1h average [pphm],2657,4370,3.848702
35,Penrith,PENRITH TEMP 1h average [°C],81,4239,66.592593
36,Penrith,PENRITH HUMID 1h average [%],236,4239,27.067797
3,Camden,CAMDEN CO 1h average [ppm],2702,2329,4.944856
2,Camden,CAMDEN NO2 1h average [pphm],2107,2056,2.783579
4,Camden,CAMDEN NO 1h average [pphm],3500,2056,2.940286
5,Camden,CAMDEN OZONE 1h average [pphm],2158,2056,2.485171
29,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],2095,991,2.618616
55,Prospect,PROSPECT PM10 1h average [µg/m³],577,850,3.691508
53,Prospect,PROSPECT PM2.5 1h average [µg/m³],3146,850,2.856325
76,Rozelle,ROZELLE RAIN 1h average [mm/m²],82,799,20.134146
14,Liverpool,LIVERPOOL CO 1h average [ppm],2936,551,11.794278
7,Camden,CAMDEN PM2.5 1h average [µg/m³],4231,530,2.349563
77,Rozelle,ROZELLE SO2 1h average [pphm],2301,379,2.421990
73,Rozelle,ROZELLE NO 1h average [pphm],3147,373,2.283127
74,Rozelle,ROZELLE OZONE 1h average [pphm],2223,373,1.609087
72,Rozelle,ROZELLE CO 1h average [ppm],2367,373,2.491762
71,Rozelle,ROZELLE NO2 1h average [pphm],2785,373,2.300539
78,Rozelle,ROZELLE PM10 1h average [µg/m³],539,361,3.166976
75,Rozelle,ROZELLE PM2.5 1h average [µg/m³],2033,360,2.203148
67,Randwick,RANDWICK WDR 1h average [°],68,356,32.205882
68,Randwick,RANDWICK WSP 1h average [m/s],68,356,32.205882
59,Randwick,RANDWICK HUMID 1h average [%],442,355,7.361991
58,Randwick,RANDWICK TEMP 1h average [°C],83,355,18.000000
17,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],2913,347,2.271541
79,Rozelle,ROZELLE WDR 1h average [°],71,289,9.098592
80,Rozelle,ROZELLE WSP 1h average [m/s],71,289,9.098592
70,Rozelle,ROZELLE HUMID 1h average [%],90,287,9.755556
69,Rozelle,ROZELLE TEMP 1h average [°C],90,287,9.577778
50,Prospect,PROSPECT CO 1h average [ppm],3535,207,4.889392
60,Randwick,RANDWICK SO2 1h average [pphm],2235,203,1.944072
25,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],2481,183,1.918581
27,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],3451,183,3.637496
51,Prospect,PROSPECT NO 1h average [pphm],3509,173,2.597321
56,Prospect,PROSPECT WDR 1h average [°],68,169,10.529412
57,Prospect,PROSPECT WSP 1h average [m/s],68,169,10.514706
54,Prospect,PROSPECT SO2 1h average [pphm],2285,168,1.590372
49,Prospect,PROSPECT NO2 1h average [pphm],2702,168,2.149889
52,Prospect,PROSPECT OZONE 1h average [pphm],2234,168,1.426141
6,Camden,CAMDEN PM10 1h average [µg/m³],910,167,2.400000
0,Camden,CAMDEN TEMP 1h average [°C],93,163,9.720430
10,Camden,CAMDEN WSP 1h average [m/s],102,163,7.441176
9,Camden,CAMDEN WDR 1h average [°],99,163,7.717172
1,Camden,CAMDEN HUMID 1h average [%],438,163,7.331050
16,Liverpool,LIVERPOOL OZONE 1h average [pphm],2269,152,1.702071
62,Randwick,RANDWICK NO 1h average [pphm],2637,147,2.227152
61,Randwick,RANDWICK NO2 1h average [pphm],2599,145,2.680646
26,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],2452,145,1.768352
63,Randwick,RANDWICK OZONE 1h average [pphm],2207,138,1.468962
31,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],2265,133,1.514349
65,Randwick,RANDWICK PM2.5 1h average [µg/m³],3009,132,2.050183
64,Randwick,RANDWICK PM10 1h average [µg/m³],493,129,2.784990
19,Liverpool,LIVERPOOL SO2 1h average [pphm],2366,119,1.794590
47,Prospect,PROSPECT TEMP 1h average [°C],88,100,8.670455
48,Prospect,PROSPECT HUMID 1h average [%],260,100,6.296154
12,Liverpool,LIVERPOOL HUMID 1h average [%],213,97,6.084507
32,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],633,97,2.115324
13,Liverpool,LIVERPOOL NO2 1h average [pphm],2808,91,2.140313
15,Liverpool,LIVERPOOL NO 1h average [pphm],2926,91,2.037594
11,Liverpool,LIVERPOOL TEMP 1h average [°C],118,60,6.610169
20,Liverpool,LIVERPOOL PM10 1h average [µg/m³],497,52,2.917505
21,Liverpool,LIVERPOOL WDR 1h average [°],103,51,3.873786
22,Liverpool,LIVERPOOL WSP 1h average [m/s],103,51,3.873786
24,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],122,33,4.803279
23,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],73,21,5.657534
28,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],2258,20,1.135075
33,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],53,12,1.943396
34,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],53,12,1.943396

##### 2.5.3 Check if Missing Gaps Suitable for Interpolation

In [14]:
# Classify missing gaps as short or prolonged.
# Gaps of up to 7 days are considered short enough to consider
# for interpolation. Longer gaps will be left as missing.

gap_threshold = 168  # 7 days × 24 hours

interpolation_summary = []

for station in retained_stations:

    df = cleaned_station_data[station].copy()

    for column in df.columns:

        if column == "Datetime":
            continue

        is_missing = df[column].isna()

        gap_group = (
            is_missing.ne(is_missing.shift())
            .cumsum()
        )

        gap_lengths = (
            df.loc[is_missing]
            .groupby(gap_group[is_missing])
            .size()
        )

        if len(gap_lengths) == 0:
            continue

        short_gaps = (gap_lengths <= gap_threshold).sum()
        long_gaps = (gap_lengths > gap_threshold).sum()

        interpolation_summary.append({
            "Station": station,
            "Variable": column,
            "Total_Gaps": len(gap_lengths),
            "Short_Gaps_<=168h": short_gaps,
            "Long_Gaps_>168h": long_gaps,
            "Longest_Gap_Hours": gap_lengths.max()
        })

interpolation_summary_df = pd.DataFrame(
    interpolation_summary
)

display(
    interpolation_summary_df.sort_values(
        "Longest_Gap_Hours",
        ascending=False
    )
)

,Station,Variable,Total_Gaps,Short_Gaps_<=168h,Long_Gaps_>168h,Longest_Gap_Hours
66,Randwick,RANDWICK RAIN 1h average [mm/m²],36,35,1,24037
30,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],34,33,1,20487
18,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],73,72,1,14800
8,Camden,CAMDEN RAIN 1h average [mm/m²],73,72,1,14488
38,Penrith,PENRITH CO 1h average [ppm],2233,2222,11,4442
40,Penrith,PENRITH OZONE 1h average [pphm],2060,2059,1,4442
43,Penrith,PENRITH SO2 1h average [pphm],2085,2083,2,4442
45,Penrith,PENRITH WDR 1h average [°],46,45,1,4427
46,Penrith,PENRITH WSP 1h average [m/s],46,45,1,4427
41,Penrith,PENRITH PM2.5 1h average [µg/m³],2809,2807,2,4384
44,Penrith,PENRITH PM10 1h average [µg/m³],554,553,1,4384
42,Penrith,PENRITH RAIN 1h average [mm/m²],65,64,1,4382
39,Penrith,PENRITH NO 1h average [pphm],2680,2679,1,4370
37,Penrith,PENRITH NO2 1h average [pphm],2657,2656,1,4370
35,Penrith,PENRITH TEMP 1h average [°C],81,79,2,4239
36,Penrith,PENRITH HUMID 1h average [%],236,234,2,4239
3,Camden,CAMDEN CO 1h average [ppm],2702,2700,2,2329
2,Camden,CAMDEN NO2 1h average [pphm],2107,2105,2,2056
4,Camden,CAMDEN NO 1h average [pphm],3500,3498,2,2056
5,Camden,CAMDEN OZONE 1h average [pphm],2158,2156,2,2056
29,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],2095,2093,2,991
55,Prospect,PROSPECT PM10 1h average [µg/m³],577,576,1,850
53,Prospect,PROSPECT PM2.5 1h average [µg/m³],3146,3143,3,850
76,Rozelle,ROZELLE RAIN 1h average [mm/m²],82,80,2,799
14,Liverpool,LIVERPOOL CO 1h average [ppm],2936,2924,12,551
7,Camden,CAMDEN PM2.5 1h average [µg/m³],4231,4229,2,530
77,Rozelle,ROZELLE SO2 1h average [pphm],2301,2298,3,379
73,Rozelle,ROZELLE NO 1h average [pphm],3147,3145,2,373
74,Rozelle,ROZELLE OZONE 1h average [pphm],2223,2222,1,373
72,Rozelle,ROZELLE CO 1h average [ppm],2367,2364,3,373
71,Rozelle,ROZELLE NO2 1h average [pphm],2785,2783,2,373
78,Rozelle,ROZELLE PM10 1h average [µg/m³],539,538,1,361
75,Rozelle,ROZELLE PM2.5 1h average [µg/m³],2033,2032,1,360
67,Randwick,RANDWICK WDR 1h average [°],68,64,4,356
68,Randwick,RANDWICK WSP 1h average [m/s],68,64,4,356
59,Randwick,RANDWICK HUMID 1h average [%],442,440,2,355
58,Randwick,RANDWICK TEMP 1h average [°C],83,81,2,355
17,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],2913,2911,2,347
79,Rozelle,ROZELLE WDR 1h average [°],71,70,1,289
80,Rozelle,ROZELLE WSP 1h average [m/s],71,70,1,289
70,Rozelle,ROZELLE HUMID 1h average [%],90,89,1,287
69,Rozelle,ROZELLE TEMP 1h average [°C],90,89,1,287
50,Prospect,PROSPECT CO 1h average [ppm],3535,3533,2,207
60,Randwick,RANDWICK SO2 1h average [pphm],2235,2234,1,203
25,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],2481,2480,1,183
27,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],3451,3450,1,183
51,Prospect,PROSPECT NO 1h average [pphm],3509,3508,1,173
56,Prospect,PROSPECT WDR 1h average [°],68,67,1,169
57,Prospect,PROSPECT WSP 1h average [m/s],68,67,1,169
54,Prospect,PROSPECT SO2 1h average [pphm],2285,2285,0,168
49,Prospect,PROSPECT NO2 1h average [pphm],2702,2702,0,168
52,Prospect,PROSPECT OZONE 1h average [pphm],2234,2234,0,168
6,Camden,CAMDEN PM10 1h average [µg/m³],910,910,0,167
0,Camden,CAMDEN TEMP 1h average [°C],93,93,0,163
10,Camden,CAMDEN WSP 1h average [m/s],102,102,0,163
9,Camden,CAMDEN WDR 1h average [°],99,99,0,163
1,Camden,CAMDEN HUMID 1h average [%],438,438,0,163
16,Liverpool,LIVERPOOL OZONE 1h average [pphm],2269,2269,0,152
62,Randwick,RANDWICK NO 1h average [pphm],2637,2637,0,147
61,Randwick,RANDWICK NO2 1h average [pphm],2599,2599,0,145
26,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],2452,2452,0,145
63,Randwick,RANDWICK OZONE 1h average [pphm],2207,2207,0,138
31,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],2265,2265,0,133
65,Randwick,RANDWICK PM2.5 1h average [µg/m³],3009,3009,0,132
64,Randwick,RANDWICK PM10 1h average [µg/m³],493,493,0,129
19,Liverpool,LIVERPOOL SO2 1h average [pphm],2366,2366,0,119
47,Prospect,PROSPECT TEMP 1h average [°C],88,88,0,100
48,Prospect,PROSPECT HUMID 1h average [%],260,260,0,100
12,Liverpool,LIVERPOOL HUMID 1h average [%],213,213,0,97
32,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],633,633,0,97
13,Liverpool,LIVERPOOL NO2 1h average [pphm],2808,2808,0,91
15,Liverpool,LIVERPOOL NO 1h average [pphm],2926,2926,0,91
11,Liverpool,LIVERPOOL TEMP 1h average [°C],118,118,0,60
20,Liverpool,LIVERPOOL PM10 1h average [µg/m³],497,497,0,52
21,Liverpool,LIVERPOOL WDR 1h average [°],103,103,0,51
22,Liverpool,LIVERPOOL WSP 1h average [m/s],103,103,0,51
24,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],122,122,0,33
23,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],73,73,0,21
28,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],2258,2258,0,20
33,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],53,53,0,12
34,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],53,53,0,12

##### 2.5.4 PM2.5 Missing-Gap Assessment

The missing-value patterns for PM2.5 are examined separately because PM2.5 is the primary target variable of this study. The distribution of missing-gap lengths is used to determine an appropriate interpolation limit while avoiding excessive estimation across prolonged periods of missing observations.

In [15]:
# Examine the distribution of PM2.5 missing-gap lengths for each retained station.

pm25_gap_details = []

for station in retained_stations:

    df = cleaned_station_data[station].copy()

    pm25_columns = [
        column for column in df.columns
        if "PM2.5" in column.upper()
    ]

    for column in pm25_columns:

        is_missing = df[column].isna()

        gap_group = is_missing.ne(is_missing.shift()).cumsum()

        gap_lengths = (
            df.loc[is_missing]
            .groupby(gap_group[is_missing])
            .size()
        )

        for gap_length in gap_lengths:
            pm25_gap_details.append({
                "Station": station,
                "Variable": column,
                "Gap_Length_Hours": gap_length
            })

pm25_gap_details_df = pd.DataFrame(pm25_gap_details)

display(
    pm25_gap_details_df.sort_values(
        ["Station", "Gap_Length_Hours"],
        ascending=[True, False]
    ).head(50)
)

     Station                         Variable  Gap_Length_Hours
2625  Camden  CAMDEN PM2.5 1h average [µg/m³]               530
2564  Camden  CAMDEN PM2.5 1h average [µg/m³]               177
939   Camden  CAMDEN PM2.5 1h average [µg/m³]               149
2036  Camden  CAMDEN PM2.5 1h average [µg/m³]                96
3327  Camden  CAMDEN PM2.5 1h average [µg/m³]                84
4189  Camden  CAMDEN PM2.5 1h average [µg/m³]                77
3342  Camden  CAMDEN PM2.5 1h average [µg/m³]                73
3336  Camden  CAMDEN PM2.5 1h average [µg/m³]                66
1516  Camden  CAMDEN PM2.5 1h average [µg/m³]                32
1085  Camden  CAMDEN PM2.5 1h average [µg/m³]                30
2475  Camden  CAMDEN PM2.5 1h average [µg/m³]                30
2742  Camden  CAMDEN PM2.5 1h average [µg/m³]                30
3419  Camden  CAMDEN PM2.5 1h average [µg/m³]                30
353   Camden  CAMDEN PM2.5 1h average [µg/m³]                29
2583  Camden  CAMDEN PM2.5 1h average [µg/m³]                27
3136  Camden  CAMDEN PM2.5 1h average [µg/m³]                27
3266  Camden  CAMDEN PM2.5 1h average [µg/m³]                26
458   Camden  CAMDEN PM2.5 1h average [µg/m³]                24
3626  Camden  CAMDEN PM2.5 1h average [µg/m³]                24
3391  Camden  CAMDEN PM2.5 1h average [µg/m³]                22
3262  Camden  CAMDEN PM2.5 1h average [µg/m³]                20
552   Camden  CAMDEN PM2.5 1h average [µg/m³]                19
3638  Camden  CAMDEN PM2.5 1h average [µg/m³]                17
3640  Camden  CAMDEN PM2.5 1h average [µg/m³]                16
3641  Camden  CAMDEN PM2.5 1h average [µg/m³]                16
1701  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
2151  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
3633  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
3635  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
3639  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
3648  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
3651  Camden  CAMDEN PM2.5 1h average [µg/m³]                15
1453  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
2170  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
3316  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
3634  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
3642  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
3667  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
3668  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
3826  Camden  CAMDEN PM2.5 1h average [µg/m³]                14
1     Camden  CAMDEN PM2.5 1h average [µg/m³]                13
553   Camden  CAMDEN PM2.5 1h average [µg/m³]                13
2672  Camden  CAMDEN PM2.5 1h average [µg/m³]                13
3627  Camden  CAMDEN PM2.5 1h average [µg/m³]                13
3629  Camden  CAMDEN PM2.5 1h average [µg/m³]                13
3643  Camden  CAMDEN PM2.5 1h average [µg/m³]                13
3673  Camden  CAMDEN PM2.5 1h average [µg/m³]                13
3653  Camden  CAMDEN PM2.5 1h average [µg/m³]                12
3672  Camden  CAMDEN PM2.5 1h average [µg/m³]                12
911   Camden  CAMDEN PM2.5 1h average [µg/m³]                11

##### 2.5.5 Selection of Interpolation Limit

Based on the observed missing-gap patterns, linear interpolation will be restricted to missing gaps of up to 48 consecutive hours. 

Longer gaps will remain missing to avoid introducing excessive estimated data across prolonged periods of unavailable observations.

In [16]:
# Summarise how many missing gaps would be interpolated using a 48-hour limit.

interpolation_limit = 48

interpolation_impact = []

for station in retained_stations:

    df = cleaned_station_data[station].copy()

    for column in df.columns:

        if column == "Datetime":
            continue

        is_missing = df[column].isna()

        gap_group = is_missing.ne(is_missing.shift()).cumsum()

        gap_lengths = (
            df.loc[is_missing]
            .groupby(gap_group[is_missing])
            .size()
        )

        if len(gap_lengths) == 0:
            continue

        gaps_to_interpolate = (gap_lengths <= interpolation_limit).sum()
        missing_values_to_interpolate = gap_lengths[
            gap_lengths <= interpolation_limit
        ].sum()

        interpolation_impact.append({
            "Station": station,
            "Variable": column,
            "Total_Missing_Gaps": len(gap_lengths),
            "Gaps_<=48h": gaps_to_interpolate,
            "Values_Eligible_for_Interpolation": missing_values_to_interpolate,
            "Longest_Gap_Hours": gap_lengths.max()
        })

interpolation_impact_df = pd.DataFrame(interpolation_impact)

display(
    interpolation_impact_df.sort_values(
        "Values_Eligible_for_Interpolation",
        ascending=False
    )
)

,Station,Variable,Total_Missing_Gaps,Gaps_<=48h,Values_Eligible_for_Interpolation,Longest_Gap_Hours
14,Liverpool,LIVERPOOL CO 1h average [ppm],2936,2794,19661,551
50,Prospect,PROSPECT CO 1h average [ppm],3535,3499,14304,207
38,Penrith,PENRITH CO 1h average [ppm],2233,2160,12000,4442
27,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],3451,3440,11542,183
3,Camden,CAMDEN CO 1h average [ppm],2702,2680,9198,2329
7,Camden,CAMDEN PM2.5 1h average [µg/m³],4231,4223,8689,530
51,Prospect,PROSPECT NO 1h average [pphm],3509,3500,8217,173
4,Camden,CAMDEN NO 1h average [pphm],3500,3492,7515,2056
73,Rozelle,ROZELLE NO 1h average [pphm],3147,3144,6529,373
53,Prospect,PROSPECT PM2.5 1h average [µg/m³],3146,3138,6133,850
61,Randwick,RANDWICK NO2 1h average [pphm],2599,2589,6052,145
41,Penrith,PENRITH PM2.5 1h average [µg/m³],2809,2805,5740,4384
13,Liverpool,LIVERPOOL NO2 1h average [pphm],2808,2804,5706,91
71,Rozelle,ROZELLE NO2 1h average [pphm],2785,2781,5692,373
15,Liverpool,LIVERPOOL NO 1h average [pphm],2926,2922,5657,91
65,Randwick,RANDWICK PM2.5 1h average [µg/m³],3009,3003,5646,132
17,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],2913,2906,5595,347
37,Penrith,PENRITH NO2 1h average [pphm],2657,2649,5225,4370
62,Randwick,RANDWICK NO 1h average [pphm],2637,2628,5025,147
49,Prospect,PROSPECT NO2 1h average [pphm],2702,2693,4918,168
39,Penrith,PENRITH NO 1h average [pphm],2680,2672,4848,4370
72,Rozelle,ROZELLE CO 1h average [ppm],2367,2353,4307,373
75,Rozelle,ROZELLE PM2.5 1h average [µg/m³],2033,2031,4059,360
25,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],2481,2474,4034,183
29,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],2095,2089,4019,991
26,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],2452,2448,4004,145
77,Rozelle,ROZELLE SO2 1h average [pphm],2301,2289,3870,379
19,Liverpool,LIVERPOOL SO2 1h average [pphm],2366,2357,3511,119
60,Randwick,RANDWICK SO2 1h average [pphm],2235,2223,3241,203
2,Camden,CAMDEN NO2 1h average [pphm],2107,2099,3091,2056
31,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],2265,2261,3076,133
54,Prospect,PROSPECT SO2 1h average [pphm],2285,2279,3060,168
16,Liverpool,LIVERPOOL OZONE 1h average [pphm],2269,2259,3033,152
1,Camden,CAMDEN HUMID 1h average [%],438,435,2911,163
5,Camden,CAMDEN OZONE 1h average [pphm],2158,2152,2864,2056
74,Rozelle,ROZELLE OZONE 1h average [pphm],2223,2217,2843,373
43,Penrith,PENRITH SO2 1h average [pphm],2085,2082,2832,4442
63,Randwick,RANDWICK OZONE 1h average [pphm],2207,2203,2819,138
52,Prospect,PROSPECT OZONE 1h average [pphm],2234,2229,2666,168
28,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],2258,2258,2563,20
40,Penrith,PENRITH OZONE 1h average [pphm],2060,2058,2443,4442
59,Randwick,RANDWICK HUMID 1h average [%],442,437,2319,355
6,Camden,CAMDEN PM10 1h average [µg/m³],910,905,1746,167
20,Liverpool,LIVERPOOL PM10 1h average [µg/m³],497,496,1398,52
48,Prospect,PROSPECT HUMID 1h average [%],260,257,1397,100
36,Penrith,PENRITH HUMID 1h average [%],236,231,1314,4239
44,Penrith,PENRITH PM10 1h average [µg/m³],554,548,1194,4384
78,Rozelle,ROZELLE PM10 1h average [µg/m³],539,535,1178,361
12,Liverpool,LIVERPOOL HUMID 1h average [%],213,211,1148,97
32,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],633,630,1126,97
64,Randwick,RANDWICK PM10 1h average [µg/m³],493,490,1052,129
55,Prospect,PROSPECT PM10 1h average [µg/m³],577,573,1043,850
11,Liverpool,LIVERPOOL TEMP 1h average [°C],118,116,669,60
0,Camden,CAMDEN TEMP 1h average [°C],93,90,604,163
70,Rozelle,ROZELLE HUMID 1h average [%],90,89,591,287
24,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],122,122,586,33
69,Rozelle,ROZELLE TEMP 1h average [°C],90,89,575,287
76,Rozelle,ROZELLE RAIN 1h average [mm/m²],82,80,565,799
58,Randwick,RANDWICK TEMP 1h average [°C],83,78,559,355
47,Prospect,PROSPECT TEMP 1h average [°C],88,85,524,100
68,Randwick,RANDWICK WSP 1h average [m/s],68,57,443,356
67,Randwick,RANDWICK WDR 1h average [°],68,57,443,356
23,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],73,73,413,21
42,Penrith,PENRITH RAIN 1h average [mm/m²],65,64,393,4382
8,Camden,CAMDEN RAIN 1h average [mm/m²],73,69,376,14488
9,Camden,CAMDEN WDR 1h average [°],99,94,362,163
10,Camden,CAMDEN WSP 1h average [m/s],102,97,357,163
22,Liverpool,LIVERPOOL WSP 1h average [m/s],103,102,348,51
21,Liverpool,LIVERPOOL WDR 1h average [°],103,102,348,51
35,Penrith,PENRITH TEMP 1h average [°C],81,76,339,4239
56,Prospect,PROSPECT WDR 1h average [°],68,64,330,169
57,Prospect,PROSPECT WSP 1h average [m/s],68,64,329,169
79,Rozelle,ROZELLE WDR 1h average [°],71,69,284,289
80,Rozelle,ROZELLE WSP 1h average [m/s],71,69,284,289
66,Randwick,RANDWICK RAIN 1h average [mm/m²],36,33,276,24037
18,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],73,72,235,14800
30,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],34,33,138,20487
45,Penrith,PENRITH WDR 1h average [°],46,45,111,4427
46,Penrith,PENRITH WSP 1h average [m/s],46,45,111,4427
33,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],53,53,103,12
34,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],53,53,103,12

##### 2.5.6 Short-Gap Linear Interpolation

Linear interpolation is applied to short missing-value gaps of up to 48 consecutive hours. 

Longer gaps are retained as missing because estimating values across prolonged periods may introduce substantial artificial variation. 

The interpolation is performed only between available observations, so gaps at the beginning or end of a series are not extrapolated.

**Rain and Wind Direction are not linearly interpolated here because their values do not behave as simple continuous linear variables.**
- Rainfall can occur as short-duration events, 
- wind direction is circular, with 0° and 360° representing the same direction. 

These variables are therefore retained for separate treatment where required.

In [22]:
# Interpolate only complete missing gaps of 48 hours or less.
# Longer gaps are left unchanged.
# Rainfall and wind direction are not interpolated.

import re

interpolated_station_data = {}

interpolation_results = []

interpolation_variables = [
    "PM2.5",
    "PM10",
    "CO",
    "NO",
    "NO2",
    "OZONE",
    "SO2",
    "TEMP",
    "HUMID",
    "WSP"
]

interpolation_limit = 48

for station in retained_stations:

    df = cleaned_station_data[station].copy()

    for column in df.columns:

        if column == "Datetime":
            continue

        column_upper = column.upper()

        # Identify the actual variable name in the column.
        # Word boundaries prevent "NO" from matching "NORTH".
        should_interpolate = any(
            re.search(
                rf"(?<![A-Z0-9]){re.escape(variable.upper())}(?![A-Z0-9])",
                column_upper
            )
            for variable in interpolation_variables
        )

        if not should_interpolate:
            continue

        original_missing = df[column].isna()

        # Identify each consecutive missing-value gap.
        gap_group = original_missing.ne(
            original_missing.shift()
        ).cumsum()

        gap_lengths = (
            df.loc[original_missing]
            .groupby(gap_group[original_missing])
            .size()
        )

        # Identify only gaps that are short enough to interpolate.
        short_gap_groups = gap_lengths[
            gap_lengths <= interpolation_limit
        ].index

        # Create a mask containing only missing values
        # belonging to short gaps.
        short_gap_mask = (
            original_missing
            & gap_group.isin(short_gap_groups)
        )

        # Temporarily interpolate the complete series.
        interpolated_series = df[column].interpolate(
            method="linear",
            limit_area="inside"
        )

        # Apply interpolated values only to eligible gaps.
        df.loc[short_gap_mask, column] = (
            interpolated_series.loc[short_gap_mask]
        )

        values_filled = (
            original_missing
            & df[column].notna()
        ).sum()

        interpolation_results.append({
            "Station": station,
            "Variable": column,
            "Values_Interpolated": values_filled
        })

    interpolated_station_data[station] = df

interpolation_results_df = pd.DataFrame(interpolation_results)

display(
    interpolation_results_df[
        interpolation_results_df["Values_Interpolated"] > 0
    ].sort_values(
        "Values_Interpolated",
        ascending=False
    )
)

print("Short-gap interpolation completed.")

,Station,Variable,Values_Interpolated
12,Liverpool,LIVERPOOL CO 1h average [ppm],19623
42,Prospect,PROSPECT CO 1h average [ppm],14304
32,Penrith,PENRITH CO 1h average [ppm],12000
23,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],11542
3,Camden,CAMDEN CO 1h average [ppm],9198
7,Camden,CAMDEN PM2.5 1h average [µg/m³],8689
43,Prospect,PROSPECT NO 1h average [pphm],8214
4,Camden,CAMDEN NO 1h average [pphm],7514
62,Rozelle,ROZELLE NO 1h average [pphm],6529
45,Prospect,PROSPECT PM2.5 1h average [µg/m³],6133
52,Randwick,RANDWICK NO2 1h average [pphm],6018
35,Penrith,PENRITH PM2.5 1h average [µg/m³],5720
60,Rozelle,ROZELLE NO2 1h average [pphm],5692
11,Liverpool,LIVERPOOL NO2 1h average [pphm],5672
13,Liverpool,LIVERPOOL NO 1h average [pphm],5623
56,Randwick,RANDWICK PM2.5 1h average [µg/m³],5612
15,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],5554
31,Penrith,PENRITH NO2 1h average [pphm],5225
53,Randwick,RANDWICK NO 1h average [pphm],4989
41,Prospect,PROSPECT NO2 1h average [pphm],4918
33,Penrith,PENRITH NO 1h average [pphm],4848
61,Rozelle,ROZELLE CO 1h average [ppm],4307
64,Rozelle,ROZELLE PM2.5 1h average [µg/m³],4059
21,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],4034
25,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],4019
22,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],4004
65,Rozelle,ROZELLE SO2 1h average [pphm],3870
16,Liverpool,LIVERPOOL SO2 1h average [pphm],3511
51,Randwick,RANDWICK SO2 1h average [pphm],3207
2,Camden,CAMDEN NO2 1h average [pphm],3091
26,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],3076
46,Prospect,PROSPECT SO2 1h average [pphm],3060
14,Liverpool,LIVERPOOL OZONE 1h average [pphm],2999
1,Camden,CAMDEN HUMID 1h average [%],2911
5,Camden,CAMDEN OZONE 1h average [pphm],2864
63,Rozelle,ROZELLE OZONE 1h average [pphm],2843
36,Penrith,PENRITH SO2 1h average [pphm],2832
54,Randwick,RANDWICK OZONE 1h average [pphm],2785
44,Prospect,PROSPECT OZONE 1h average [pphm],2666
24,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],2563
34,Penrith,PENRITH OZONE 1h average [pphm],2443
50,Randwick,RANDWICK HUMID 1h average [%],2285
6,Camden,CAMDEN PM10 1h average [µg/m³],1746
40,Prospect,PROSPECT HUMID 1h average [%],1397
17,Liverpool,LIVERPOOL PM10 1h average [µg/m³],1363
30,Penrith,PENRITH HUMID 1h average [%],1314
37,Penrith,PENRITH PM10 1h average [µg/m³],1194
66,Rozelle,ROZELLE PM10 1h average [µg/m³],1178
27,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],1126
10,Liverpool,LIVERPOOL HUMID 1h average [%],1114
47,Prospect,PROSPECT PM10 1h average [µg/m³],1043
55,Randwick,RANDWICK PM10 1h average [µg/m³],1018
9,Liverpool,LIVERPOOL TEMP 1h average [°C],635
0,Camden,CAMDEN TEMP 1h average [°C],604
59,Rozelle,ROZELLE HUMID 1h average [%],591
20,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],586
58,Rozelle,ROZELLE TEMP 1h average [°C],575
49,Randwick,RANDWICK TEMP 1h average [°C],525
39,Prospect,PROSPECT TEMP 1h average [°C],524
19,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],413
57,Randwick,RANDWICK WSP 1h average [m/s],409
8,Camden,CAMDEN WSP 1h average [m/s],357
29,Penrith,PENRITH TEMP 1h average [°C],339
48,Prospect,PROSPECT WSP 1h average [m/s],329
18,Liverpool,LIVERPOOL WSP 1h average [m/s],314
67,Rozelle,ROZELLE WSP 1h average [m/s],284
38,Penrith,PENRITH WSP 1h average [m/s],111
28,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],103

Short-gap interpolation completed.

###### Also, the fact that some variables have fewer values interpolated than the number of values that were eligible in 2.5.5 is fine. For example:

###### - Liverpool CO: 19,661 eligible → 19,623 actually interpolated
###### - Camden PM2.5: 8,689 eligible → 8,689 actually interpolated
###### - Penrith PM2.5: 5,740 eligible → 5,720 actually interpolated

###### That's because limit_area="inside" prevents interpolation when a gap is at the beginning or end of the available series. We don't extrapolate beyond observed data.

##### 2.5.7 Post-Interpolation Verification

The interpolated datasets are checked to confirm that short missing-value gaps have been filled as intended, while excluded variables and prolonged missing-value gaps remain unchanged. The checks also confirm that the interpolation process has not altered the hourly timestamp structure.

In [24]:
# Verify the results of short-gap interpolation.

#Section 1: Timestamp and row-count check
print("=== 1. Timestamp and row-count check ===")

for station in retained_stations:

    original_df = cleaned_station_data[station]
    interpolated_df = interpolated_station_data[station]

    print(
        f"{station}: "
        f"rows before = {len(original_df):,}, "
        f"rows after = {len(interpolated_df):,}, "
        f"timestamps unchanged = "
        f"{original_df['Datetime'].equals(interpolated_df['Datetime'])}"
    )

# Section 2: Checking variables that were excluded from interpolation
print("\n=== 2. Excluded variables check ===")

excluded_check = []

for station in retained_stations:

    original_df = cleaned_station_data[station]
    interpolated_df = interpolated_station_data[station]

    for column in original_df.columns:

        if column == "Datetime":
            continue

        column_upper = column.upper()

        if "RAIN" in column_upper or "WDR" in column_upper:

            changed = not original_df[column].equals(
                interpolated_df[column]
            )

            excluded_check.append({
                "Station": station,
                "Variable": column,
                "Changed": changed
            })

excluded_check_df = pd.DataFrame(excluded_check)

display(excluded_check_df)

print(
    "Excluded-variable values changed:",
    excluded_check_df["Changed"].any()
)

# Section 3: Checking for missing values (those gaps >48hours)
print("\n=== 3. Remaining missing values ===")

remaining_missing = []

for station in retained_stations:

    df = interpolated_station_data[station]

    for column in df.columns:

        if column == "Datetime":
            continue

        missing_count = df[column].isna().sum()

        remaining_missing.append({
            "Station": station,
            "Variable": column,
            "Remaining_Missing_Values": missing_count
        })

remaining_missing_df = pd.DataFrame(remaining_missing)

display(
    remaining_missing_df[
        remaining_missing_df["Remaining_Missing_Values"] > 0
    ].sort_values(
        "Remaining_Missing_Values",
        ascending=False
    )
)

# Section 4: Missing PM2.5 values for long gaps 
print("\n=== 4. PM2.5 missing values after interpolation ===")

pm25_missing_check = []

for station in retained_stations:

    df = interpolated_station_data[station]

    pm25_columns = [
        column
        for column in df.columns
        if "PM2.5" in column.upper()
    ]

    for column in pm25_columns:

        pm25_missing_check.append({
            "Station": station,
            "Variable": column,
            "Remaining_Missing_PM2.5": df[column].isna().sum()
        })

pm25_missing_check_df = pd.DataFrame(pm25_missing_check)

display(pm25_missing_check_df)


print("\nPost-interpolation verification completed.")

=== 1. Timestamp and row-count check ===
Camden: rows before = 57,384, rows after = 57,384, timestamps unchanged = True
Liverpool: rows before = 57,384, rows after = 57,384, timestamps unchanged = True
Parramatta North: rows before = 57,384, rows after = 57,384, timestamps unchanged = True
Penrith: rows before = 57,384, rows after = 57,384, timestamps unchanged = True
Prospect: rows before = 57,384, rows after = 57,384, timestamps unchanged = True
Randwick: rows before = 57,384, rows after = 57,384, timestamps unchanged = True
Rozelle: rows before = 57,384, rows after = 57,384, timestamps unchanged = True

=== 2. Excluded variables check ===

             Station                                  Variable  Changed
0             Camden            CAMDEN RAIN 1h average [mm/m²]    False
1             Camden                 CAMDEN WDR 1h average [°]    False
2          Liverpool         LIVERPOOL RAIN 1h average [mm/m²]    False
3          Liverpool              LIVERPOOL WDR 1h average [°]    False
4   Parramatta North  PARRAMATTA NORTH RAIN 1h average [mm/m²]    False
5   Parramatta North       PARRAMATTA NORTH WDR 1h average [°]    False
6            Penrith           PENRITH RAIN 1h average [mm/m²]    False
7            Penrith                PENRITH WDR 1h average [°]    False
8           Prospect               PROSPECT WDR 1h average [°]    False
9           Randwick          RANDWICK RAIN 1h average [mm/m²]    False
10          Randwick               RANDWICK WDR 1h average [°]    False
11           Rozelle           ROZELLE RAIN 1h average [mm/m²]    False
12           Rozelle                ROZELLE WDR 1h average [°]    False

Excluded-variable values changed: False

=== 3. Remaining missing values ===

,Station,Variable,Remaining_Missing_Values
66,Randwick,RANDWICK RAIN 1h average [mm/m²],24524
30,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],20625
8,Camden,CAMDEN RAIN 1h average [mm/m²],15164
18,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],15035
14,Liverpool,LIVERPOOL CO 1h average [ppm],15005
38,Penrith,PENRITH CO 1h average [ppm],13478
36,Penrith,PENRITH HUMID 1h average [%],5074
35,Penrith,PENRITH TEMP 1h average [°C],5055
39,Penrith,PENRITH NO 1h average [pphm],5002
37,Penrith,PENRITH NO2 1h average [pphm],5001
43,Penrith,PENRITH SO2 1h average [pphm],4858
42,Penrith,PENRITH RAIN 1h average [mm/m²],4775
44,Penrith,PENRITH PM10 1h average [µg/m³],4759
41,Penrith,PENRITH PM2.5 1h average [µg/m³],4713
45,Penrith,PENRITH WDR 1h average [°],4538
40,Penrith,PENRITH OZONE 1h average [pphm],4532
46,Penrith,PENRITH WSP 1h average [m/s],4427
3,Camden,CAMDEN CO 1h average [ppm],4163
50,Prospect,PROSPECT CO 1h average [ppm],2980
53,Prospect,PROSPECT PM2.5 1h average [µg/m³],2853
4,Camden,CAMDEN NO 1h average [pphm],2777
2,Camden,CAMDEN NO2 1h average [pphm],2774
5,Camden,CAMDEN OZONE 1h average [pphm],2499
67,Randwick,RANDWICK WDR 1h average [°],2190
68,Randwick,RANDWICK WSP 1h average [m/s],1781
77,Rozelle,ROZELLE SO2 1h average [pphm],1703
76,Rozelle,ROZELLE RAIN 1h average [mm/m²],1651
72,Rozelle,ROZELLE CO 1h average [ppm],1591
29,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],1467
7,Camden,CAMDEN PM2.5 1h average [µg/m³],1252
60,Randwick,RANDWICK SO2 1h average [pphm],1138
55,Prospect,PROSPECT PM10 1h average [µg/m³],1087
17,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],1063
27,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],1011
59,Randwick,RANDWICK HUMID 1h average [%],969
58,Randwick,RANDWICK TEMP 1h average [°C],969
61,Randwick,RANDWICK NO2 1h average [pphm],949
51,Prospect,PROSPECT NO 1h average [pphm],900
49,Prospect,PROSPECT NO2 1h average [pphm],891
62,Randwick,RANDWICK NO 1h average [pphm],884
16,Liverpool,LIVERPOOL OZONE 1h average [pphm],863
9,Camden,CAMDEN WDR 1h average [°],764
19,Liverpool,LIVERPOOL SO2 1h average [pphm],735
74,Rozelle,ROZELLE OZONE 1h average [pphm],734
25,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],726
56,Prospect,PROSPECT WDR 1h average [°],716
71,Rozelle,ROZELLE NO2 1h average [pphm],715
73,Rozelle,ROZELLE NO 1h average [pphm],656
79,Rozelle,ROZELLE WDR 1h average [°],646
54,Prospect,PROSPECT SO2 1h average [pphm],574
65,Randwick,RANDWICK PM2.5 1h average [µg/m³],557
78,Rozelle,ROZELLE PM10 1h average [µg/m³],529
52,Prospect,PROSPECT OZONE 1h average [pphm],520
63,Randwick,RANDWICK OZONE 1h average [pphm],457
6,Camden,CAMDEN PM10 1h average [µg/m³],438
75,Rozelle,ROZELLE PM2.5 1h average [µg/m³],420
10,Camden,CAMDEN WSP 1h average [m/s],402
21,Liverpool,LIVERPOOL WDR 1h average [°],399
57,Prospect,PROSPECT WSP 1h average [m/s],386
80,Rozelle,ROZELLE WSP 1h average [m/s],362
64,Randwick,RANDWICK PM10 1h average [µg/m³],355
31,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],354
15,Liverpool,LIVERPOOL NO 1h average [pphm],339
13,Liverpool,LIVERPOOL NO2 1h average [pphm],338
26,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],332
0,Camden,CAMDEN TEMP 1h average [°C],300
1,Camden,CAMDEN HUMID 1h average [%],300
69,Rozelle,ROZELLE TEMP 1h average [°C],287
70,Rozelle,ROZELLE HUMID 1h average [%],287
48,Prospect,PROSPECT HUMID 1h average [%],240
47,Prospect,PROSPECT TEMP 1h average [°C],239
32,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],213
12,Liverpool,LIVERPOOL HUMID 1h average [%],182
11,Liverpool,LIVERPOOL TEMP 1h average [°C],145
33,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],103
20,Liverpool,LIVERPOOL PM10 1h average [µg/m³],87
22,Liverpool,LIVERPOOL WSP 1h average [m/s],85

=== 4. PM2.5 missing values after interpolation ===

,Station,Variable,Remaining_Missing_PM2.5
0,Camden,CAMDEN PM2.5 1h average [µg/m³],1252
1,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],1063
2,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],1467
3,Penrith,PENRITH PM2.5 1h average [µg/m³],4713
4,Prospect,PROSPECT PM2.5 1h average [µg/m³],2853
5,Randwick,RANDWICK PM2.5 1h average [µg/m³],557
6,Rozelle,ROZELLE PM2.5 1h average [µg/m³],420

Post-interpolation verification completed.

##### 2.5.8 Final Missing-Value Summary

After short-gap interpolation, the remaining missing values are summarised for each station and variable. These remaining gaps primarily represent prolonged periods of unavailable observations that were intentionally not interpolated. The summary is retained to document the completeness of the datasets used for subsequent analysis.

In [25]:
# Summarise missing values remaining after short-gap interpolation.

final_missing_summary = []

for station in retained_stations:

    df = interpolated_station_data[station]

    for column in df.columns:

        if column == "Datetime":
            continue

        missing_count = df[column].isna().sum()
        total_count = len(df)
        missing_percentage = (missing_count / total_count) * 100

        final_missing_summary.append({
            "Station": station,
            "Variable": column,
            "Remaining_Missing_Values": missing_count,
            "Total_Values": total_count,
            "Missing_Percentage": missing_percentage
        })

final_missing_summary_df = pd.DataFrame(final_missing_summary)

display(
    final_missing_summary_df.sort_values(
        "Missing_Percentage",
        ascending=False
    )
)

print("Final missing-value summary completed.")

,Station,Variable,Remaining_Missing_Values,Total_Values,Missing_Percentage
66,Randwick,RANDWICK RAIN 1h average [mm/m²],24524,57384,42.736651
30,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],20625,57384,35.942074
8,Camden,CAMDEN RAIN 1h average [mm/m²],15164,57384,26.425484
18,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],15035,57384,26.200683
14,Liverpool,LIVERPOOL CO 1h average [ppm],15005,57384,26.148404
38,Penrith,PENRITH CO 1h average [ppm],13478,57384,23.487383
36,Penrith,PENRITH HUMID 1h average [%],5074,57384,8.842186
35,Penrith,PENRITH TEMP 1h average [°C],5055,57384,8.809076
39,Penrith,PENRITH NO 1h average [pphm],5002,57384,8.716715
37,Penrith,PENRITH NO2 1h average [pphm],5001,57384,8.714973
43,Penrith,PENRITH SO2 1h average [pphm],4858,57384,8.465774
42,Penrith,PENRITH RAIN 1h average [mm/m²],4775,57384,8.321135
44,Penrith,PENRITH PM10 1h average [µg/m³],4759,57384,8.293252
41,Penrith,PENRITH PM2.5 1h average [µg/m³],4713,57384,8.213091
45,Penrith,PENRITH WDR 1h average [°],4538,57384,7.908128
40,Penrith,PENRITH OZONE 1h average [pphm],4532,57384,7.897672
46,Penrith,PENRITH WSP 1h average [m/s],4427,57384,7.714694
3,Camden,CAMDEN CO 1h average [ppm],4163,57384,7.254635
50,Prospect,PROSPECT CO 1h average [ppm],2980,57384,5.193085
53,Prospect,PROSPECT PM2.5 1h average [µg/m³],2853,57384,4.971769
4,Camden,CAMDEN NO 1h average [pphm],2777,57384,4.839328
2,Camden,CAMDEN NO2 1h average [pphm],2774,57384,4.834100
5,Camden,CAMDEN OZONE 1h average [pphm],2499,57384,4.354872
67,Randwick,RANDWICK WDR 1h average [°],2190,57384,3.816395
68,Randwick,RANDWICK WSP 1h average [m/s],1781,57384,3.103653
77,Rozelle,ROZELLE SO2 1h average [pphm],1703,57384,2.967726
76,Rozelle,ROZELLE RAIN 1h average [mm/m²],1651,57384,2.877109
72,Rozelle,ROZELLE CO 1h average [ppm],1591,57384,2.772550
29,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],1467,57384,2.556462
7,Camden,CAMDEN PM2.5 1h average [µg/m³],1252,57384,2.181793
60,Randwick,RANDWICK SO2 1h average [pphm],1138,57384,1.983131
55,Prospect,PROSPECT PM10 1h average [µg/m³],1087,57384,1.894256
17,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],1063,57384,1.852433
27,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],1011,57384,1.761815
58,Randwick,RANDWICK TEMP 1h average [°C],969,57384,1.688624
59,Randwick,RANDWICK HUMID 1h average [%],969,57384,1.688624
61,Randwick,RANDWICK NO2 1h average [pphm],949,57384,1.653771
51,Prospect,PROSPECT NO 1h average [pphm],900,57384,1.568381
49,Prospect,PROSPECT NO2 1h average [pphm],891,57384,1.552698
62,Randwick,RANDWICK NO 1h average [pphm],884,57384,1.540499
16,Liverpool,LIVERPOOL OZONE 1h average [pphm],863,57384,1.503904
9,Camden,CAMDEN WDR 1h average [°],764,57384,1.331382
19,Liverpool,LIVERPOOL SO2 1h average [pphm],735,57384,1.280845
74,Rozelle,ROZELLE OZONE 1h average [pphm],734,57384,1.279102
25,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],726,57384,1.265161
56,Prospect,PROSPECT WDR 1h average [°],716,57384,1.247735
71,Rozelle,ROZELLE NO2 1h average [pphm],715,57384,1.245992
73,Rozelle,ROZELLE NO 1h average [pphm],656,57384,1.143176
79,Rozelle,ROZELLE WDR 1h average [°],646,57384,1.125749
54,Prospect,PROSPECT SO2 1h average [pphm],574,57384,1.000279
65,Randwick,RANDWICK PM2.5 1h average [µg/m³],557,57384,0.970654
78,Rozelle,ROZELLE PM10 1h average [µg/m³],529,57384,0.921860
52,Prospect,PROSPECT OZONE 1h average [pphm],520,57384,0.906176
63,Randwick,RANDWICK OZONE 1h average [pphm],457,57384,0.796389
6,Camden,CAMDEN PM10 1h average [µg/m³],438,57384,0.763279
75,Rozelle,ROZELLE PM2.5 1h average [µg/m³],420,57384,0.731911
10,Camden,CAMDEN WSP 1h average [m/s],402,57384,0.700544
21,Liverpool,LIVERPOOL WDR 1h average [°],399,57384,0.695316
57,Prospect,PROSPECT WSP 1h average [m/s],386,57384,0.672661
80,Rozelle,ROZELLE WSP 1h average [m/s],362,57384,0.630838
64,Randwick,RANDWICK PM10 1h average [µg/m³],355,57384,0.618639
31,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],354,57384,0.616897
15,Liverpool,LIVERPOOL NO 1h average [pphm],339,57384,0.590757
13,Liverpool,LIVERPOOL NO2 1h average [pphm],338,57384,0.589014
26,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],332,57384,0.578558
1,Camden,CAMDEN HUMID 1h average [%],300,57384,0.522794
0,Camden,CAMDEN TEMP 1h average [°C],300,57384,0.522794
69,Rozelle,ROZELLE TEMP 1h average [°C],287,57384,0.500139
70,Rozelle,ROZELLE HUMID 1h average [%],287,57384,0.500139
48,Prospect,PROSPECT HUMID 1h average [%],240,57384,0.418235
47,Prospect,PROSPECT TEMP 1h average [°C],239,57384,0.416492
32,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],213,57384,0.371184
12,Liverpool,LIVERPOOL HUMID 1h average [%],182,57384,0.317162
11,Liverpool,LIVERPOOL TEMP 1h average [°C],145,57384,0.252684
33,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],103,57384,0.179493
20,Liverpool,LIVERPOOL PM10 1h average [µg/m³],87,57384,0.151610
22,Liverpool,LIVERPOOL WSP 1h average [m/s],85,57384,0.148125
34,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],0,57384,0.000000
23,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],0,57384,0.000000
24,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],0,57384,0.000000
28,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],0,57384,0.000000

Final missing-value summary completed.

In [26]:
# Save the final missing-value summary for documentation and later reference.

final_missing_summary_path = tables_dir / "final_missing_value_summary.csv"

final_missing_summary_df.to_csv(
    final_missing_summary_path,
    index=False
)

print(f"Saved final missing-value summary to: {final_missing_summary_path}")

Saved final missing-value summary to: ..\results\tables\final_missing_value_summary.csv

#### 2.6 Final Dataset Preparation and Checks

##### 2.6.1 Selection of Analysis Variables

The final analysis datasets are restricted to the variables defined for the study. PM2.5 is retained as the target variable, while temperature, humidity, wind speed, wind direction, rainfall, PM10, NO2, CO, NO, OZONE, and SO2 are retained as potential predictor variables. The timestamp is also retained to preserve the temporal structure of the observations.

In [35]:
# Select the final analysis variables using exact variable-name matching.
# This prevents variables such as "NO" from matching text inside
# station names such as "NORTH".

import re

analysis_variables = [
    "PM2.5",
    "TEMP",
    "HUMID",
    "WSP",
    "WDR",
    "RAIN",
    "PM10",
    "NO2",
    "CO",
    "NO",
    "OZONE",
    "SO2"
]

final_station_data = {}

for station in retained_stations:

    df = interpolated_station_data[station].copy()

    selected_columns = ["Datetime"]

    for variable in analysis_variables:

        matching_columns = []

        for column in df.columns:

            if column == "Datetime":
                continue

            column_upper = column.upper()

            # Match the variable as a separate token.
            # This prevents "NO" from matching "NORTH".
            pattern = rf"(?<![A-Z0-9]){re.escape(variable.upper())}(?![A-Z0-9])"

            if re.search(pattern, column_upper):
                matching_columns.append(column)

        if len(matching_columns) == 1:
            selected_columns.append(matching_columns[0])

        elif len(matching_columns) > 1:
            print(
                f"WARNING: Multiple matches for {station} - {variable}: "
                f"{matching_columns}"
            )

        else:
            print(
                f"\nNOTE: {station} - {variable} is not available.\n"
            )

    final_station_data[station] = df[selected_columns].copy()

    print(
        f"{station}: "
        f"{final_station_data[station].shape[0]:,} rows, "
        f"{final_station_data[station].shape[1] - 1} analysis variables"
    )

print("\nFinal analysis variables selected.")

NOTE: Camden - SO2 is not available.

Camden: 57,384 rows, 11 analysis variables
Liverpool: 57,384 rows, 12 analysis variables
Parramatta North: 57,384 rows, 12 analysis variables
Penrith: 57,384 rows, 12 analysis variables

NOTE: Prospect - RAIN is not available.

Prospect: 57,384 rows, 11 analysis variables

NOTE: Randwick - CO is not available.

Randwick: 57,384 rows, 11 analysis variables
Rozelle: 57,384 rows, 12 analysis variables

Final analysis variables selected.

In [33]:
print("Parramatta North selected columns:")

for column in final_station_data["Parramatta North"].columns:
    print(column)

Parramatta North selected columns:
Datetime
PARRAMATTA NORTH PM2.5 1h average [µg/m³]
PARRAMATTA NORTH TEMP 1h average [°C]
PARRAMATTA NORTH HUMID 1h average [%]
PARRAMATTA NORTH WSP 1h average [m/s]
PARRAMATTA NORTH WDR 1h average [°]
PARRAMATTA NORTH RAIN 1h average [mm/m²]
PARRAMATTA NORTH PM10 1h average [µg/m³]
PARRAMATTA NORTH NO2 1h average [pphm]
PARRAMATTA NORTH CO 1h average [ppm]
PARRAMATTA NORTH NO 1h average [pphm]
PARRAMATTA NORTH OZONE 1h average [pphm]
PARRAMATTA NORTH SO2 1h average [pphm]

##### 2.6.2 Duplicate Timestamp Check

The final station datasets are checked for duplicate timestamps to confirm that each station contains at most one observation for each hourly timestamp. This ensures that the final datasets maintain the expected hourly temporal structure.

In [36]:
# Check for duplicate timestamps in the final station datasets.

duplicate_timestamp_summary = []

for station in retained_stations:

    df = final_station_data[station]

    duplicate_count = df["Datetime"].duplicated().sum()

    duplicate_timestamp_summary.append({
        "Station": station,
        "Total_Rows": len(df),
        "Duplicate_Timestamps": duplicate_count
    })

duplicate_timestamp_summary_df = pd.DataFrame(
    duplicate_timestamp_summary
)

display(duplicate_timestamp_summary_df)

print(
    "\nTotal duplicate timestamps across all stations:",
    duplicate_timestamp_summary_df["Duplicate_Timestamps"].sum()
)

            Station  Total_Rows  Duplicate_Timestamps
0            Camden       57384                     0
1         Liverpool       57384                     0
2  Parramatta North       57384                     0
3           Penrith       57384                     0
4          Prospect       57384                     0
5          Randwick       57384                     0
6           Rozelle       57384                     0

Total duplicate timestamps across all stations: 0

##### 2.6.3 Final Physical-Validity Check

A final physical-validity check is performed after interpolation to confirm that the cleaned datasets do not contain observations outside the predefined physical ranges. This verifies that the preprocessing steps have not introduced new physically invalid measurements.

In [37]:
# Check for physically invalid values in the final analysis datasets.

final_invalid_summary = []

for station in retained_stations:

    df = final_station_data[station]

    for column in df.columns:

        if column == "Datetime":
            continue

        column_upper = column.upper()

        if "HUMID" in column_upper:
            invalid = (df[column] < 0) | (df[column] > 100)

        elif "PM2.5" in column_upper or "PM10" in column_upper:
            invalid = df[column] < 0

        elif "WDR" in column_upper:
            invalid = (df[column] < 0) | (df[column] > 360)

        elif "WSP" in column_upper or "RAIN" in column_upper:
            invalid = df[column] < 0

        elif any(
            pollutant in column_upper
            for pollutant in ["NO2", "NO", "CO", "OZONE", "SO2"]
        ):
            invalid = df[column] < 0

        else:
            continue

        invalid_count = invalid.sum()

        if invalid_count > 0:
            final_invalid_summary.append({
                "Station": station,
                "Variable": column,
                "Invalid_Values": invalid_count
            })

final_invalid_summary_df = pd.DataFrame(final_invalid_summary)

if final_invalid_summary_df.empty:

    print("No physically invalid values detected.")

else:

    display(
        final_invalid_summary_df.sort_values(
            "Invalid_Values",
            ascending=False
        )
    )

No physically invalid values detected.

##### 2.6.4 Final Data-Range Check

The minimum and maximum observed values of the final analysis variables are examined for each station. This provides a final descriptive check of the data ranges before exploratory analysis. The check is used to identify potentially unusual distributions for further investigation during EDA rather than automatically removing observations.

In [38]:
# Summarise the observed ranges of the final analysis variables.

final_range_summary = []

for station in retained_stations:

    df = final_station_data[station]

    for column in df.columns:

        if column == "Datetime":
            continue

        final_range_summary.append({
            "Station": station,
            "Variable": column,
            "Minimum": df[column].min(),
            "Maximum": df[column].max()
        })

final_range_summary_df = pd.DataFrame(final_range_summary)

display(
    final_range_summary_df.sort_values(
        ["Station", "Variable"]
    )
)

print("Final data-range check completed.")

,Station,Variable,Minimum,Maximum
8,Camden,CAMDEN CO 1h average [ppm],0.0,4.9
2,Camden,CAMDEN HUMID 1h average [%],9.3,100.0
9,Camden,CAMDEN NO 1h average [pphm],0.0,6.0
7,Camden,CAMDEN NO2 1h average [pphm],0.0,4.1
10,Camden,CAMDEN OZONE 1h average [pphm],0.0,11.5
6,Camden,CAMDEN PM10 1h average [µg/m³],0.0,1199.0
0,Camden,CAMDEN PM2.5 1h average [µg/m³],0.0,513.0
5,Camden,CAMDEN RAIN 1h average [mm/m²],0.0,60.6
1,Camden,CAMDEN TEMP 1h average [°C],-1.6,45.2
4,Camden,CAMDEN WDR 1h average [°],0.0,360.0
3,Camden,CAMDEN WSP 1h average [m/s],0.0,11.2
19,Liverpool,LIVERPOOL CO 1h average [ppm],0.0,2.4
13,Liverpool,LIVERPOOL HUMID 1h average [%],8.4,100.0
20,Liverpool,LIVERPOOL NO 1h average [pphm],0.0,29.0
18,Liverpool,LIVERPOOL NO2 1h average [pphm],0.0,6.3
21,Liverpool,LIVERPOOL OZONE 1h average [pphm],0.0,10.3
17,Liverpool,LIVERPOOL PM10 1h average [µg/m³],0.0,1545.8
11,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],0.0,183.7
16,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],0.0,52.6
22,Liverpool,LIVERPOOL SO2 1h average [pphm],0.0,2.4
12,Liverpool,LIVERPOOL TEMP 1h average [°C],1.4,46.8
15,Liverpool,LIVERPOOL WDR 1h average [°],0.0,360.0
14,Liverpool,LIVERPOOL WSP 1h average [m/s],0.0,11.7
31,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],0.0,4.7
25,Parramatta North,PARRAMATTA NORTH HUMID 1h average [%],7.9,100.0
32,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],0.0,32.0
30,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],0.0,4.7
33,Parramatta North,PARRAMATTA NORTH OZONE 1h average [pphm],0.0,10.7
29,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],0.0,803.7
23,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],0.0,136.6
28,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],0.0,39.8
34,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],0.0,3.6
24,Parramatta North,PARRAMATTA NORTH TEMP 1h average [°C],1.5,46.4
27,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],0.0,360.0
26,Parramatta North,PARRAMATTA NORTH WSP 1h average [m/s],0.0,6.0
43,Penrith,PENRITH CO 1h average [ppm],0.0,14.1
37,Penrith,PENRITH HUMID 1h average [%],0.0,100.0
44,Penrith,PENRITH NO 1h average [pphm],0.0,11.9
42,Penrith,PENRITH NO2 1h average [pphm],0.0,3.7
45,Penrith,PENRITH OZONE 1h average [pphm],0.0,9.8
41,Penrith,PENRITH PM10 1h average [µg/m³],0.0,14073.1
35,Penrith,PENRITH PM2.5 1h average [µg/m³],0.0,162.6
40,Penrith,PENRITH RAIN 1h average [mm/m²],0.0,62.8
46,Penrith,PENRITH SO2 1h average [pphm],0.0,1.9
36,Penrith,PENRITH TEMP 1h average [°C],-0.7,43.0
39,Penrith,PENRITH WDR 1h average [°],0.0,360.0
38,Penrith,PENRITH WSP 1h average [m/s],0.0,12.7
54,Prospect,PROSPECT CO 1h average [ppm],0.0,2.1
49,Prospect,PROSPECT HUMID 1h average [%],7.8,100.0
55,Prospect,PROSPECT NO 1h average [pphm],0.0,23.3
53,Prospect,PROSPECT NO2 1h average [pphm],0.0,4.9
56,Prospect,PROSPECT OZONE 1h average [pphm],0.0,10.2
52,Prospect,PROSPECT PM10 1h average [µg/m³],0.0,933.3
47,Prospect,PROSPECT PM2.5 1h average [µg/m³],0.0,145.8
57,Prospect,PROSPECT SO2 1h average [pphm],0.0,2.6
48,Prospect,PROSPECT TEMP 1h average [°C],1.5,45.9
51,Prospect,PROSPECT WDR 1h average [°],0.0,360.0
50,Prospect,PROSPECT WSP 1h average [m/s],0.0,11.0
60,Randwick,RANDWICK HUMID 1h average [%],9.1,100.0
66,Randwick,RANDWICK NO 1h average [pphm],0.0,24.1
65,Randwick,RANDWICK NO2 1h average [pphm],0.0,12.8
67,Randwick,RANDWICK OZONE 1h average [pphm],0.0,9.0
64,Randwick,RANDWICK PM10 1h average [µg/m³],0.0,544.7
58,Randwick,RANDWICK PM2.5 1h average [µg/m³],0.0,556.3
63,Randwick,RANDWICK RAIN 1h average [mm/m²],0.0,42.4
68,Randwick,RANDWICK SO2 1h average [pphm],0.0,3.6
59,Randwick,RANDWICK TEMP 1h average [°C],2.7,41.7
62,Randwick,RANDWICK WDR 1h average [°],0.0,360.0
61,Randwick,RANDWICK WSP 1h average [m/s],0.0,11.7
77,Rozelle,ROZELLE CO 1h average [ppm],0.0,3.3
71,Rozelle,ROZELLE HUMID 1h average [%],9.2,99.2
78,Rozelle,ROZELLE NO 1h average [pphm],0.0,14.1
76,Rozelle,ROZELLE NO2 1h average [pphm],0.0,5.0
79,Rozelle,ROZELLE OZONE 1h average [pphm],0.0,8.3
75,Rozelle,ROZELLE PM10 1h average [µg/m³],0.0,420.2
69,Rozelle,ROZELLE PM2.5 1h average [µg/m³],0.0,159.7
74,Rozelle,ROZELLE RAIN 1h average [mm/m²],0.0,49.8
80,Rozelle,ROZELLE SO2 1h average [pphm],0.0,3.9
70,Rozelle,ROZELLE TEMP 1h average [°C],4.0,42.2
73,Rozelle,ROZELLE WDR 1h average [°],0.0,360.0
72,Rozelle,ROZELLE WSP 1h average [m/s],0.0,19.2

Final data-range check completed.

###### There are some very large maxima, especially:

###### - Camden PM10: 1,199.0
###### - Liverpool PM10: 1,545.8
###### - Penrith PM10: 14,073.1
###### - Camden PM2.5: 513.0
###### - Randwick PM2.5: 556.3

###### But we are NOT removing these here. This is exactly why we are doing the EDA next: we'll inspect distributions and boxplots and determine whether these are genuine extreme observations, data-quality issues, or values that need special treatment.

##### 2.6.5 Saving Final Station Datasets

The final preprocessed datasets for the retained stations are saved as CSV files for use in subsequent exploratory analysis and modelling. The datasets retain the hourly timestamp structure, selected analysis variables, cleaned physically invalid observations, and interpolated values for eligible short missing gaps.

In [41]:
# Save the final preprocessed dataset for each retained station.

final_processed_dir = processed_dir.parent / "final"

final_processed_dir.mkdir(
    parents=True,
    exist_ok=True
)

for station in retained_stations:

    df = final_station_data[station].copy()

    output_path = final_processed_dir / f"{station}_final_preprocessed.csv"

    df.to_csv(
        output_path,
        index=False
    )

    print(
        f"{station}: saved to {output_path}"
    )

print("\nAll final station datasets have been saved.")

Camden: saved to ..\data\final\Camden_final_preprocessed.csv
Liverpool: saved to ..\data\final\Liverpool_final_preprocessed.csv
Parramatta North: saved to ..\data\final\Parramatta North_final_preprocessed.csv
Penrith: saved to ..\data\final\Penrith_final_preprocessed.csv
Prospect: saved to ..\data\final\Prospect_final_preprocessed.csv
Randwick: saved to ..\data\final\Randwick_final_preprocessed.csv
Rozelle: saved to ..\data\final\Rozelle_final_preprocessed.csv

All final station datasets have been saved.

#### 2.7 Handling of Remaining Missing Values

After short-gap interpolation, some missing values remain because they belong to prolonged gaps or variables that were excluded from ordinary linear interpolation (Wind direction, Rain). These remaining missing values are not filled artificially at this preprocessing stage.

The retained missing values will be considered during Exploratory Data Analysis (EDA) to assess their temporal and station-level patterns. For subsequent machine learning, rows with missing target or predictor values will be handled when constructing the modelling datasets, according to the requirements of each modelling approach.

This approach avoids introducing potentially unreliable estimates across prolonged periods of unavailable observations while preserving the original missing-data information for further analysis.

In [43]:
# Summarise the remaining missing values in the final station datasets.

remaining_missing_summary = []

for station in retained_stations:

    df = final_station_data[station]

    for column in df.columns:

        if column == "Datetime":
            continue

        missing_count = df[column].isna().sum()

        if missing_count > 0:
            remaining_missing_summary.append({
                "Station": station,
                "Variable": column,
                "Missing_Values": missing_count,
                "Total_Values": len(df),
                "Missing_Percentage": (
                    missing_count / len(df)
                ) * 100
            })

remaining_missing_summary_df = pd.DataFrame(
    remaining_missing_summary
)

display(
    remaining_missing_summary_df.sort_values(
        "Missing_Percentage",
        ascending=False
    )
)

,Station,Variable,Missing_Values,Total_Values,Missing_Percentage
59,Randwick,RANDWICK RAIN 1h average [mm/m²],24524,57384,42.736651
25,Parramatta North,PARRAMATTA NORTH RAIN 1h average [mm/m²],20625,57384,35.942074
5,Camden,CAMDEN RAIN 1h average [mm/m²],15164,57384,26.425484
16,Liverpool,LIVERPOOL RAIN 1h average [mm/m²],15035,57384,26.200683
19,Liverpool,LIVERPOOL CO 1h average [ppm],15005,57384,26.148404
39,Penrith,PENRITH CO 1h average [ppm],13478,57384,23.487383
33,Penrith,PENRITH HUMID 1h average [%],5074,57384,8.842186
32,Penrith,PENRITH TEMP 1h average [°C],5055,57384,8.809076
40,Penrith,PENRITH NO 1h average [pphm],5002,57384,8.716715
38,Penrith,PENRITH NO2 1h average [pphm],5001,57384,8.714973
42,Penrith,PENRITH SO2 1h average [pphm],4858,57384,8.465774
36,Penrith,PENRITH RAIN 1h average [mm/m²],4775,57384,8.321135
37,Penrith,PENRITH PM10 1h average [µg/m³],4759,57384,8.293252
31,Penrith,PENRITH PM2.5 1h average [µg/m³],4713,57384,8.213091
35,Penrith,PENRITH WDR 1h average [°],4538,57384,7.908128
41,Penrith,PENRITH OZONE 1h average [pphm],4532,57384,7.897672
34,Penrith,PENRITH WSP 1h average [m/s],4427,57384,7.714694
8,Camden,CAMDEN CO 1h average [ppm],4163,57384,7.254635
50,Prospect,PROSPECT CO 1h average [ppm],2980,57384,5.193085
43,Prospect,PROSPECT PM2.5 1h average [µg/m³],2853,57384,4.971769
9,Camden,CAMDEN NO 1h average [pphm],2777,57384,4.839328
7,Camden,CAMDEN NO2 1h average [pphm],2774,57384,4.834100
10,Camden,CAMDEN OZONE 1h average [pphm],2499,57384,4.354872
58,Randwick,RANDWICK WDR 1h average [°],2190,57384,3.816395
57,Randwick,RANDWICK WSP 1h average [m/s],1781,57384,3.103653
76,Rozelle,ROZELLE SO2 1h average [pphm],1703,57384,2.967726
70,Rozelle,ROZELLE RAIN 1h average [mm/m²],1651,57384,2.877109
73,Rozelle,ROZELLE CO 1h average [ppm],1591,57384,2.772550
23,Parramatta North,PARRAMATTA NORTH PM2.5 1h average [µg/m³],1467,57384,2.556462
0,Camden,CAMDEN PM2.5 1h average [µg/m³],1252,57384,2.181793
64,Randwick,RANDWICK SO2 1h average [pphm],1138,57384,1.983131
48,Prospect,PROSPECT PM10 1h average [µg/m³],1087,57384,1.894256
11,Liverpool,LIVERPOOL PM2.5 1h average [µg/m³],1063,57384,1.852433
29,Parramatta North,PARRAMATTA NORTH NO 1h average [pphm],1011,57384,1.761815
56,Randwick,RANDWICK HUMID 1h average [%],969,57384,1.688624
55,Randwick,RANDWICK TEMP 1h average [°C],969,57384,1.688624
61,Randwick,RANDWICK NO2 1h average [pphm],949,57384,1.653771
51,Prospect,PROSPECT NO 1h average [pphm],900,57384,1.568381
49,Prospect,PROSPECT NO2 1h average [pphm],891,57384,1.552698
62,Randwick,RANDWICK NO 1h average [pphm],884,57384,1.540499
21,Liverpool,LIVERPOOL OZONE 1h average [pphm],863,57384,1.503904
4,Camden,CAMDEN WDR 1h average [°],764,57384,1.331382
22,Liverpool,LIVERPOOL SO2 1h average [pphm],735,57384,1.280845
75,Rozelle,ROZELLE OZONE 1h average [pphm],734,57384,1.279102
27,Parramatta North,PARRAMATTA NORTH NO2 1h average [pphm],726,57384,1.265161
47,Prospect,PROSPECT WDR 1h average [°],716,57384,1.247735
72,Rozelle,ROZELLE NO2 1h average [pphm],715,57384,1.245992
74,Rozelle,ROZELLE NO 1h average [pphm],656,57384,1.143176
69,Rozelle,ROZELLE WDR 1h average [°],646,57384,1.125749
53,Prospect,PROSPECT SO2 1h average [pphm],574,57384,1.000279
54,Randwick,RANDWICK PM2.5 1h average [µg/m³],557,57384,0.970654
71,Rozelle,ROZELLE PM10 1h average [µg/m³],529,57384,0.921860
52,Prospect,PROSPECT OZONE 1h average [pphm],520,57384,0.906176
63,Randwick,RANDWICK OZONE 1h average [pphm],457,57384,0.796389
6,Camden,CAMDEN PM10 1h average [µg/m³],438,57384,0.763279
65,Rozelle,ROZELLE PM2.5 1h average [µg/m³],420,57384,0.731911
3,Camden,CAMDEN WSP 1h average [m/s],402,57384,0.700544
15,Liverpool,LIVERPOOL WDR 1h average [°],399,57384,0.695316
46,Prospect,PROSPECT WSP 1h average [m/s],386,57384,0.672661
68,Rozelle,ROZELLE WSP 1h average [m/s],362,57384,0.630838
60,Randwick,RANDWICK PM10 1h average [µg/m³],355,57384,0.618639
30,Parramatta North,PARRAMATTA NORTH SO2 1h average [pphm],354,57384,0.616897
20,Liverpool,LIVERPOOL NO 1h average [pphm],339,57384,0.590757
18,Liverpool,LIVERPOOL NO2 1h average [pphm],338,57384,0.589014
28,Parramatta North,PARRAMATTA NORTH CO 1h average [ppm],332,57384,0.578558
2,Camden,CAMDEN HUMID 1h average [%],300,57384,0.522794
1,Camden,CAMDEN TEMP 1h average [°C],300,57384,0.522794
66,Rozelle,ROZELLE TEMP 1h average [°C],287,57384,0.500139
67,Rozelle,ROZELLE HUMID 1h average [%],287,57384,0.500139
45,Prospect,PROSPECT HUMID 1h average [%],240,57384,0.418235
44,Prospect,PROSPECT TEMP 1h average [°C],239,57384,0.416492
26,Parramatta North,PARRAMATTA NORTH PM10 1h average [µg/m³],213,57384,0.371184
13,Liverpool,LIVERPOOL HUMID 1h average [%],182,57384,0.317162
12,Liverpool,LIVERPOOL TEMP 1h average [°C],145,57384,0.252684
24,Parramatta North,PARRAMATTA NORTH WDR 1h average [°],103,57384,0.179493
17,Liverpool,LIVERPOOL PM10 1h average [µg/m³],87,57384,0.151610
14,Liverpool,LIVERPOOL WSP 1h average [m/s],85,57384,0.148125

#### 2.8 Preprocessing Summary

The preprocessing stage combined the available air-quality and meteorological variables for the seven retained monitoring stations. Physically invalid and suspicious negative measurements were converted to missing values rather than deleting the corresponding timestamps. Missing-value patterns were then assessed, and linear interpolation was applied only to short gaps of up to 48 consecutive hours for suitable continuous variables. Rainfall and wind direction were excluded from ordinary linear interpolation, while prolonged missing-value gaps were retained as missing.

The final datasets were checked for duplicate timestamps and physically invalid values. The resulting station-level datasets preserve the hourly temporal structure and contain the selected analysis variables available at each station. These final preprocessed datasets are saved for use in the exploratory data analysis stage.

In [45]:
print("Notebook 02 preprocessing completed successfully.")
print(f"Final datasets saved for {len(retained_stations)} retained stations.")
print("Next stage: Exploratory Data Analysis (Notebook 03).")
print("Handling of the long-gap missing values/WindDir and Rain will be done in EDA")

Notebook 02 preprocessing completed successfully.
Final datasets saved for 7 retained stations.
Next stage: Exploratory Data Analysis (Notebook 03).
Handling of the long-gap missing values/WindDir and Rain will be done in EDA